"""Regression tests for the ``codd init``/``codd greenfield`` scan.source_dirs default.

``codd init`` (and ``codd greenfield``, which delegates to it — see
``GreenfieldPipeline._run_init``) hardcoded a freshly-generated project's
``scan.source_dirs: ["src/"]`` regardless of ``--language``, even though the
selected language's profile may declare more than one first-party
``layout.source_sets`` root. C++'s profile
(``codd/languages/profiles/cpp.yaml``) is the sharpest example: it
conventionally splits public headers into ``include/<package>/``
(source_set id ``include``, role ``first_party_public``) from implementation
in ``src/`` (source_set id ``src``) — but since the init default never
consulted the profile at all, every C++ project generated by
``codd greenfield --language cpp`` had its public headers silently outside
``scan.source_dirs``: invisible to ``codd scan``'s import/call extraction and
to the DAG's ``impl_file`` node discovery
(``codd/dag/builder.py::_add_impl_files``), and therefore to dependency
analysis / VB coverage accounting for anything declared purely in a header.
Confirmed live in the ``cpp_v2_ExprCalc`` dogfood project: ``.codd/dag.json``
had 3 ``impl_file`` nodes (all under ``src/``) and ZERO for any of its 5
``include/*.hpp`` headers.

The fix (``codd.cli._default_scan_source_dirs``) resolves the language
profile generically (mirrors
``codd.project_types._resolve_kernel_language_profile``: degrade to the
historical ``["src/"]`` baseline on any resolution failure) and unions in any
additional LITERAL ``source_sets`` roots the profile declares that are not
already covered by an existing entry — no ``language == "cpp"`` branch
anywhere. These tests prove:

1. A fresh C++ project's generated ``codd.yaml`` now scans ``include/`` too.
2. An existing single-source-root language (Python) is byte-identical to
   before — the fix is additive, not a behavior change for the common case.
3. An ``include/`` file is ACTUALLY walked as source by the shared
   ``codd.discovery.iter_source_files`` walker once ``scan.source_dirs`` is
   read back out of the generated config — not just present in the YAML.
"""

from __future__ import annotations

from pathlib import Path

from click.testing import CliRunner
import yaml

from codd.cli import main
from codd.discovery import iter_source_files


def _scan_source_dirs(dest: Path, config_dir: str = "codd") -> list[str]:
    data = yaml.safe_load((dest / config_dir / "codd.yaml").read_text(encoding="utf-8"))
    return (data.get("scan") or {}).get("source_dirs") or []


def _init(dest: Path, *, name: str, language: str):
    dest.mkdir(parents=True, exist_ok=True)
    return CliRunner().invoke(
        main,
        ["init", name, "--language", language, "--dest", str(dest), "--no-suggest-lexicons"],
    )


def test_cpp_init_scans_include_dir_alongside_src(tmp_path: Path) -> None:
    """`codd init <name> --language cpp` must list BOTH src/ and include/."""
    dest = tmp_path / "proj"

    result = _init(dest, name="exprcalc", language="cpp")

    assert result.exit_code == 0, result.output
    source_dirs = _scan_source_dirs(dest)
    assert "src/" in source_dirs
    assert "include/" in source_dirs


def test_cpp_alias_cxx_also_scans_include_dir(tmp_path: Path) -> None:
    """The ``cpp`` profile's aliases (e.g. ``c++``) resolve the same way."""
    dest = tmp_path / "proj"

    result = _init(dest, name="exprcalc", language="c++")

    assert result.exit_code == 0, result.output
    assert "include/" in _scan_source_dirs(dest)


def test_python_init_source_dirs_unchanged(tmp_path: Path) -> None:
    """Backward compat: a single-source-root language keeps the exact ["src/"] default."""
    dest = tmp_path / "proj"

    result = _init(dest, name="todo", language="python")

    assert result.exit_code == 0, result.output
    assert _scan_source_dirs(dest) == ["src/"]


def test_unknown_language_degrades_to_legacy_default(tmp_path: Path) -> None:
    """An unresolvable --language must never crash init; it keeps the ["src/"] baseline."""
    dest = tmp_path / "proj"

    result = _init(dest, name="mystery", language="not-a-real-language")

    assert result.exit_code == 0, result.output
    assert _scan_source_dirs(dest) == ["src/"]


def test_cpp_include_headers_are_actually_walked_as_source(tmp_path: Path) -> None:
    """End-to-end: a header living only under include/ is discoverable as source.

    Reproduces the real dogfood gap: a public header with no counterpart under
    src/ (e.g. a header-only declaration) must be reachable through the SAME
    ``scan.source_dirs``-driven walker (``codd.discovery.iter_source_files``)
    that ``codd/scanner.py`` and the DAG builder's ``impl_file`` discovery use.
    """
    dest = tmp_path / "proj"
    result = _init(dest, name="exprcalc", language="cpp")
    assert result.exit_code == 0, result.output

    (dest / "src" / "exprcalc").mkdir(parents=True)
    (dest / "src" / "exprcalc" / "tokenizer.cpp").write_text("// impl\n", encoding="utf-8")
    (dest / "include" / "exprcalc").mkdir(parents=True)
    (dest / "include" / "exprcalc" / "tokenizer.hpp").write_text(
        "// header-only public declaration\n", encoding="utf-8"
    )

    source_dirs = _scan_source_dirs(dest)
    found = {p.name for p in iter_source_files(dest, source_dirs=source_dirs)}

    assert "tokenizer.cpp" in found
    assert "tokenizer.hpp" in found, (
        "include/ header must be discoverable via scan.source_dirs — this is "
        "the exact gap confirmed in the live cpp_v2_ExprCalc dogfood project "
        "(.codd/dag.json had 0 impl_file nodes for any of its 5 include/ headers)."
    )
