"""Verifiable-behavior (VB) coverage audit.

Test documents generated by ``codd generate`` declare a design-to-test
traceability table whose first column is a stable ``VB-<id>`` identifier, one
row per verifiable behavior. This module reconciles that declared universe
against ``codd: covers vb=<id>`` markers in test code, mirroring the
operational E2E audit semantics (explicit covers markers, explicit blockers,
orphan-marker reverse reconciliation).

The parser is header-text independent: any Markdown table whose first cell is
a ``VB-`` style id is a traceability row, so Japanese/English/any-language
headers all work. The marker grammar is shared with
``codd.operational_e2e_audit`` (subject alternation ``operation=``/``vb=``).
"""

from __future__ import annotations

import json
import re
from dataclasses import asdict, dataclass, field
from pathlib import Path, PurePosixPath
from typing import Any, Callable, Iterable

from codd.operational_e2e_audit import (
    _BLOCKER_MARKER_RE,
    _COVER_MARKER_RE,
    _DOD_MARKER_RE,
    _iter_test_files,
    _load_optional_config,
    _md_cell,
    _rel_path,
    _resolve_vb_scan_dirs,
)
from codd.path_safety import resolve_project_path

VB_AUDIT_CONTRACT_VERSION = "verifiable-behavior-audit/v1"

# First-cell id pattern: `VB-` followed by an alphanumeric id body. Header
# rows ("#", "ID", "検証可能ビヘイビア", ...) and separator rows never match.
_VB_ID_RE = re.compile(r"^VB-[A-Za-z0-9][A-Za-z0-9_.-]*$", re.IGNORECASE)
_TABLE_ROW_RE = re.compile(r"^\s*\|(?P<cells>.+)\|\s*$")
_FENCE_RE = re.compile(r"^\s*(```|~~~)")
_DEFAULT_VB_DOC_DIR = "docs/test"
# A single ``vb=<id>`` token. A ``covers`` line may carry several of them
# (``# codd: covers vb=22 vb=23 vb=24``); the shared cover regex captures only
# the first and lets its greedy trailing-details group swallow the rest, so the
# VB audit re-scans the matched span with this token regex to recover every id.
_VB_TOKEN_RE = re.compile(r"vb\s*=\s*(?P<vb>[A-Za-z0-9_.:-]+)", re.IGNORECASE)

# A ``VB-*`` token appearing anywhere in free text / a non-first table cell — a
# REFERENCE to a canonical id, not a declaration. Anchored by id-boundary
# look-arounds so it matches a standalone token (``VB-CLI-007``) but not a
# substring inside a longer identifier. Mirrors the body shape of ``_VB_ID_RE``
# (which is whole-cell anchored) so a first-cell declaration and a later-column
# reference recover the SAME id text. Used only by :func:`parse_vb_references`.
_VB_REF_RE = re.compile(
    r"(?<![A-Za-z0-9_.-])VB-[A-Za-z0-9][A-Za-z0-9_.-]*(?![A-Za-z0-9_.-])",
    re.IGNORECASE,
)

# Canonical verifiable-behavior declaration doc. Exactly ONE generated test
# document owns the VB id namespace (declares every VB once in a first-column
# ``VB-*`` table); every other test doc references those canonical ids in a
# later column instead of minting a parallel ``VB-*`` table. This prevents two
# docs from declaring the same numeric id with different semantics — the
# structural defect that makes 100% coverage impossible (see
# parse_vb_table / load_verifiable_behaviors "first wins" dedup).
_CANONICAL_VB_NODE_ID = "test:test-strategy"
_CANONICAL_VB_OUTPUT_PATH = "docs/test/test_strategy.md"


def is_canonical_vb_doc(node_id: str | None = None, output_path: str | None = None) -> bool:
    """Whether a test doc is the canonical VB declaration document.

    The canonical doc (``test:test-strategy`` / ``docs/test/test_strategy.md``)
    is the sole owner of the VB id namespace. Matching is generic: any project
    whose test-strategy node/path uses the standard CoDD naming is canonical.
    Detection accepts either the node id or the output path so it works both at
    generation time (node id known) and audit time (only paths on disk).
    """

    if node_id is not None:
        normalized_node = node_id.strip().replace("\\", "/").casefold()
        if normalized_node == _CANONICAL_VB_NODE_ID:
            return True
    if output_path is not None:
        normalized_path = output_path.strip().replace("\\", "/").casefold()
        if normalized_path == _CANONICAL_VB_OUTPUT_PATH:
            return True
        # Tolerate an absolute or nested path whose tail is the canonical file.
        if normalized_path.endswith("/" + _CANONICAL_VB_OUTPUT_PATH):
            return True
        if PurePosixPath(normalized_path).name == "test_strategy.md":
            return True
    return False


def wave_config_plans_canonical_vb_doc(config: dict[str, Any] | None) -> bool:
    """Whether the project's ``wave_config`` plans the canonical VB registry doc.

    Structural signal that this project INTENDS to declare verifiable behaviors:
    one of its planned generation artifacts is the canonical VB document
    (``test:test-strategy`` / ``docs/test/test_strategy.md``). Mirrors the
    detection in ``codd.planner._set_canonical_vb_doc_config`` (which pins the
    canonical doc into ``test_coverage.docs`` at plan time). Generic — keys off
    the standard CoDD canonical naming, never any one project's specifics.
    """

    wave_config = (config or {}).get("wave_config")
    if not isinstance(wave_config, dict):
        return False
    for entries in wave_config.values():
        if not isinstance(entries, list):
            continue
        for entry in entries:
            if not isinstance(entry, dict):
                continue
            node_id = entry.get("node_id") or entry.get("id")
            output = entry.get("output")
            if is_canonical_vb_doc(
                node_id=node_id if isinstance(node_id, str) else None,
                output_path=output if isinstance(output, str) else None,
            ):
                return True
    return False


def project_expects_vb_registry(
    project_root: Path | str,
    config: dict[str, Any] | None = None,
) -> bool:
    """Whether this project is expected to own a canonical VB registry.

    The greenfield VB-registry gates (generate-time completeness gate and the
    implement-stage empty-registry hard-fail) apply ONLY to projects that have a
    verifiable-behavior SURFACE — never to a legitimate minimal project that
    genuinely declares no behaviors. A project "expects" a VB registry when ANY
    of these structural signals hold:

    1. its ``wave_config`` plans the canonical VB document
       (:func:`wave_config_plans_canonical_vb_doc`),
    2. ``test_coverage.docs`` is explicitly configured (the planner pins the
       canonical doc here, and an owner may set it directly), or
    3. a canonical VB document already exists among the discovered test docs.

    All three are generic/structural — no project proper-names. A project with
    none of these (e.g. an app whose plan declares only design docs and no test
    strategy) is NOT gated: it has no VB surface to certify, exactly as the
    brownfield "nothing to audit -> pass" rule already allows.
    """

    project_root = Path(project_root).resolve()
    if config is None:
        config = _load_optional_config(project_root)

    if wave_config_plans_canonical_vb_doc(config):
        return True

    section = (config or {}).get("test_coverage")
    if isinstance(section, dict) and section.get("docs"):
        return True

    for doc_path in discover_vb_documents(project_root, config=config):
        if is_canonical_vb_doc(output_path=_rel_path(doc_path, project_root)):
            return True
    return False


@dataclass(frozen=True)
class VBDeclarationIssue:
    """A VB-declaration coherence problem detected across test documents."""

    kind: str  # "collision" | "noncanonical_declaration" | "duplicate" | "range_shorthand"
    severity: str  # "error" | "warning"
    vb_id: str
    message: str
    docs: tuple[str, ...] = ()


@dataclass(frozen=True)
class VBReference:
    """A ``VB-*`` token REFERENCED (not declared) in a doc's later table cells.

    Distinct from :class:`VerifiableBehavior` (a first-column DECLARATION): a
    reference points AT a canonical id from somewhere else (an acceptance-
    criteria row, a traceability column). A reference is never a declaration —
    using one as a declaration source is the structural defect this module
    guards against (the dogfood failure where AC tables reference ``VB-*`` ids
    that the canonical registry never declares).
    """

    vb_id: str
    source_doc: str
    row_id: str = ""
    context: str = ""


@dataclass(frozen=True)
class VBRegistryIssue:
    """A canonical-VB-registry completeness problem (greenfield generate gate).

    Reported by :func:`validate_vb_registry_completeness`:

    * ``missing_canonical_doc`` — the canonical VB registry doc
      (``docs/test/test_strategy.md`` / ``test:test-strategy``), the VB
      namespace owner, is absent.
    * ``empty_canonical_registry`` — the canonical doc exists but declares zero
      first-column ``VB-*`` rows.
    * ``unresolved_reference`` — a ``VB-*`` id referenced in a non-canonical
      doc's later columns is not declared in the canonical doc.
    """

    kind: str  # "missing_canonical_doc" | "empty_canonical_registry" | "unresolved_reference"
    severity: str  # "error" | "warning"
    vb_id: str = ""
    source_doc: str = ""
    message: str = ""


# Range-shorthand atomicity: a VB id must name exactly ONE behavior. A
# declaration like ``VB-EVAL-02..06`` (an ellipsis range) or ``VB-02,03,04`` (a
# comma list) collapses several behaviors into one id, which destroys
# auditability — a single ``covers`` marker cannot prove five behaviors, and the
# range is never minted as atomic rows, so the "missing" members read as
# permanently uncovered. We forbid the SHORTHAND at declaration time and require
# the generator to emit one atomic row per behavior. (We do NOT eat the shorthand
# by expanding it on the marker side — that would re-introduce the false-coverage
# this gate exists to prevent.) The ``..`` ellipsis and an in-id comma are the
# unambiguous shorthand spellings; a plain hyphenated scheme (``VB-AUTH-1``) is
# left untouched.
_VB_RANGE_SHORTHAND_RE = re.compile(r"(\.\.|,|;|…|〜|～)")


def validate_vb_declarations(
    behaviors_by_doc: dict[str, list[VerifiableBehavior]],
    *,
    canonical_doc: str | None = None,
    strict: bool = False,
) -> list[VBDeclarationIssue]:
    """Validate that the declared VB namespace is coherent across documents.

    DECLARATION validation only — it never touches coverage semantics (no alias
    tables, no similarity matching). It reports:

    * **collision** (always ERROR): the same normalized VB id is declared in two
      or more docs with DIFFERENT descriptions — an incoherent namespace where
      one id means two things.
    * **duplicate** (always WARNING): the same id+description declared in more
      than one doc — redundant but coherent.
    * **noncanonical_declaration**: a non-canonical doc declares first-column
      ``VB-*`` rows. ERROR under ``strict`` (new/CI/greenfield), WARNING with
      migration guidance otherwise (existing brownfield docs).

    ``behaviors_by_doc`` maps each doc's display path to its parsed VB rows.
    ``canonical_doc`` is the display path of the canonical declarer when known;
    otherwise canonical-ness is inferred from the standard CoDD naming.
    """

    issues: list[VBDeclarationIssue] = []

    def _is_canonical(doc: str) -> bool:
        if canonical_doc is not None:
            return doc == canonical_doc
        return is_canonical_vb_doc(output_path=doc)

    # --- collisions / duplicates across docs (normalized id) ----------------
    grouped: dict[str, list[VerifiableBehavior]] = {}
    for doc, behaviors in behaviors_by_doc.items():
        for behavior in behaviors:
            grouped.setdefault(_normalize_vb_id(behavior.vb_id), []).append(behavior)

    for normalized_id, group in sorted(grouped.items()):
        docs = sorted({behavior.source_doc or "" for behavior in group})
        if len(docs) < 2:
            continue
        descriptions = {behavior.description.strip().casefold() for behavior in group}
        display_id = group[0].vb_id
        if len(descriptions) > 1:
            issues.append(
                VBDeclarationIssue(
                    kind="collision",
                    severity="error",
                    vb_id=display_id,
                    docs=tuple(docs),
                    message=(
                        f"VB id `{display_id}` is declared with different descriptions in "
                        f"multiple documents ({', '.join(docs)}); the VB namespace is "
                        "incoherent. Declare each verifiable behavior exactly once in the "
                        f"canonical doc (`{_CANONICAL_VB_OUTPUT_PATH}`) and reference it "
                        "elsewhere — never re-mint the same id with a different meaning."
                    ),
                )
            )
        else:
            issues.append(
                VBDeclarationIssue(
                    kind="duplicate",
                    severity="warning",
                    vb_id=display_id,
                    docs=tuple(docs),
                    message=(
                        f"VB id `{display_id}` is declared identically in multiple documents "
                        f"({', '.join(docs)}); keep a single canonical declaration and "
                        "reference it from the other doc(s)."
                    ),
                )
            )

    # --- range-shorthand atomicity (always ERROR) ---------------------------
    # A VB id that packs a range/list (``VB-EVAL-02..06``) is not atomic: it names
    # several behaviors under one id, so it can never be honestly covered by one
    # test marker. Flagged in EVERY doc (canonical or not) — atomicity is a
    # property of the id itself, independent of where it is declared.
    seen_range: set[tuple[str, str]] = set()
    for doc in sorted(behaviors_by_doc):
        for behavior in behaviors_by_doc[doc]:
            if not _VB_RANGE_SHORTHAND_RE.search(behavior.vb_id):
                continue
            key = (doc, behavior.vb_id)
            if key in seen_range:
                continue
            seen_range.add(key)
            issues.append(
                VBDeclarationIssue(
                    kind="range_shorthand",
                    severity="error",
                    vb_id=behavior.vb_id,
                    docs=(doc,),
                    message=(
                        f"VB id `{behavior.vb_id}` in `{doc}` uses range/list shorthand; a "
                        "verifiable-behavior id must be ATOMIC (name exactly one behavior). "
                        "Expand it into one row per behavior with a distinct id (e.g. "
                        "`VB-EVAL-02`, `VB-EVAL-03`, …). A range cannot be honestly covered by a "
                        "single `codd: covers vb=` marker, and its members would read as "
                        "permanently uncovered."
                    ),
                )
            )

    # --- non-canonical docs that declare first-column VB rows ---------------
    for doc in sorted(behaviors_by_doc):
        behaviors = behaviors_by_doc[doc]
        if not behaviors or _is_canonical(doc):
            continue
        sample = ", ".join(sorted({behavior.vb_id for behavior in behaviors})[:5])
        issues.append(
            VBDeclarationIssue(
                kind="noncanonical_declaration",
                severity="error" if strict else "warning",
                vb_id=sample,
                docs=(doc,),
                message=(
                    f"`{doc}` declares first-column VB id(s) ({sample}), but it is not the "
                    f"canonical VB document (`{_CANONICAL_VB_OUTPUT_PATH}`). Move every "
                    "auditable VB row into the canonical doc and convert this table to a "
                    "reference mapping (first column AC-*/requirement id; canonical VB ids "
                    "in a later column). Do not add duplicate markers to tests as the fix."
                ),
            )
        )

    return issues


def parse_vb_tables_by_doc(
    project_root: Path,
    *,
    config: dict[str, Any] | None = None,
    docs: Iterable[Path | str] | None = None,
) -> dict[str, list[VerifiableBehavior]]:
    """Parse each discovered test doc's VB table, keyed by display path.

    Unlike :func:`load_verifiable_behaviors` (which dedups across docs, "first
    wins"), this keeps per-doc declarations so a collision validator can see all
    sources of a given id.
    """

    project_root = Path(project_root).resolve()
    by_doc: dict[str, list[VerifiableBehavior]] = {}
    for doc_path in discover_vb_documents(project_root, config=config, docs=docs):
        try:
            text = doc_path.read_text(encoding="utf-8")
        except (OSError, UnicodeDecodeError):
            continue
        display = _rel_path(doc_path, project_root)
        by_doc[display] = parse_vb_table(text, source_doc=display)
    return by_doc


@dataclass(frozen=True)
class VerifiableBehavior:
    """One declared verifiable behavior from a test-document VB table."""

    vb_id: str
    description: str
    source_doc: str
    declared_scenarios: str = ""


@dataclass(frozen=True)
class VBCoverEvidence:
    """A ``codd: covers vb=<id>`` claim found in a test file."""

    path: str
    vb_id: str
    details: str = ""


@dataclass(frozen=True)
class VBBlockerEvidence:
    """A ``codd: blocked vb=<id> reason=<reason>`` claim found in a test file."""

    path: str
    vb_id: str
    reason: str
    details: str = ""


@dataclass(frozen=True)
class OrphanVBMarker:
    """A vb-subject marker whose VB id is declared in no VB table."""

    path: str
    vb_id: str
    marker_kind: str  # covers / blocked / dod

    @property
    def message(self) -> str:
        return (
            f"[orphan_vb_marker] Test `{self.path}` claims `codd: {self.marker_kind} "
            f"vb={self.vb_id}`, but no test document declares `{self.vb_id}` in a "
            f"VB traceability table. Declare the behavior in the test document or "
            f"fix the marker if the id is wrong/renamed."
        )


@dataclass
class VBAuditRow:
    """Audit row for one declared verifiable behavior."""

    vb_id: str
    description: str
    source_doc: str
    coverage_status: str  # covered / blocked / uncovered
    matched_tests: list[str] = field(default_factory=list)
    blocker_reason: str = ""
    blocker_details: str = ""
    blocker_evidence: list[str] = field(default_factory=list)
    suggested_next_action: str = ""


@dataclass
class VBAuditReport:
    """Serializable verifiable-behavior coverage audit report."""

    version: str
    summary: dict[str, int | str]
    rows: list[VBAuditRow]
    orphan_vb_markers: list[OrphanVBMarker] = field(default_factory=list)

    @property
    def uncovered_rows(self) -> list[VBAuditRow]:
        return [row for row in self.rows if row.coverage_status == "uncovered"]


def parse_vb_table(markdown_text: str, *, source_doc: str = "") -> list[VerifiableBehavior]:
    """Extract VB rows from Markdown text, ignoring header wording entirely.

    A row qualifies when its first cell (after stripping inline formatting) is
    a ``VB-<id>``. Fenced code blocks are skipped so examples never count.
    """

    behaviors: list[VerifiableBehavior] = []
    in_fence = False
    for line in markdown_text.splitlines():
        if _FENCE_RE.match(line):
            in_fence = not in_fence
            continue
        if in_fence:
            continue
        match = _TABLE_ROW_RE.match(line)
        if not match:
            continue
        cells = [cell.strip() for cell in match.group("cells").split("|")]
        if not cells:
            continue
        first = cells[0].strip("`*_ ").strip()
        if not _VB_ID_RE.match(first):
            continue
        behaviors.append(
            VerifiableBehavior(
                vb_id=first,
                description=cells[1] if len(cells) > 1 else "",
                source_doc=source_doc,
                declared_scenarios=" | ".join(cells[2:]) if len(cells) > 2 else "",
            )
        )
    return behaviors


def parse_vb_references(markdown_text: str, *, source_doc: str = "") -> list[VBReference]:
    """Extract ``VB-*`` REFERENCES from a doc's table rows (not declarations).

    Mirror image of :func:`parse_vb_table`. A table row whose FIRST cell is a
    ``VB-*`` id is a DECLARATION and is skipped here entirely (it belongs to the
    declaration parser). For every OTHER row, any ``VB-*`` token found in the
    non-first cells is recorded as a reference carrying the canonical id, the
    source doc, the first cell as ``row_id`` (e.g. an ``AC-05`` acceptance-
    criteria id), and the raw row as ``context``. Fenced code blocks are skipped
    so examples never count. A reference is NEVER promoted to a declaration —
    it is only ever a candidate id for repair feedback.
    """

    refs: list[VBReference] = []
    in_fence = False
    for line in markdown_text.splitlines():
        if _FENCE_RE.match(line):
            in_fence = not in_fence
            continue
        if in_fence:
            continue
        match = _TABLE_ROW_RE.match(line)
        if not match:
            continue
        cells = [cell.strip() for cell in match.group("cells").split("|")]
        if len(cells) < 2:
            continue
        first = cells[0].strip("`*_ ").strip()
        # A first-cell VB-* is a DECLARATION (owned by parse_vb_table), never a
        # reference — so the same id is not double-counted as both.
        if _VB_ID_RE.match(first):
            continue
        for cell in cells[1:]:
            for token in _VB_REF_RE.finditer(cell):
                refs.append(
                    VBReference(
                        vb_id=token.group(0),
                        source_doc=source_doc,
                        row_id=first,
                        context=line.strip(),
                    )
                )
    return refs


def validate_vb_registry_completeness(
    project_root: Path | str,
    config: dict[str, Any] | None = None,
    *,
    strict: bool = True,
) -> list[VBRegistryIssue]:
    """Validate that the canonical VB registry is present, non-empty, and resolves.

    DECLARATION/REFERENCE coherence only — it never derives declarations from
    references or markers (that direction is forbidden; see the module docstring
    and :func:`parse_vb_references`). Returns issues for:

    * ``missing_canonical_doc`` (error) — no discovered test doc is the canonical
      VB registry (``docs/test/test_strategy.md`` / ``test:test-strategy``).
    * ``empty_canonical_registry`` (error) — the canonical doc exists but declares
      zero first-column ``VB-*`` rows.
    * ``unresolved_reference`` (error when ``strict``, else warning) — a ``VB-*``
      referenced in a non-canonical doc's later columns is not declared in the
      canonical doc.

    Reuses :func:`parse_vb_tables_by_doc` (declarations per doc) and
    :func:`parse_vb_references` (references per doc), and the module's canonical-
    doc resolution (:func:`is_canonical_vb_doc`). Range/list shorthand, collisions
    and duplicate semantics remain the job of :func:`validate_vb_declarations` —
    this function is strictly about registry COMPLETENESS, not id atomicity.
    """

    project_root = Path(project_root).resolve()
    if config is None:
        config = _load_optional_config(project_root)

    # Registry COMPLETENESS scans the WHOLE test-doc tree, NOT just the docs
    # pinned in ``test_coverage.docs``. That pin names the canonical DECLARER for
    # the coverage audit; completeness must additionally see every doc that
    # REFERENCES VB ids (e.g. an acceptance-criteria doc) so an unresolved
    # reference is caught. So discover docs by the directory tree here, ignoring
    # the ``test_coverage.docs`` constraint.
    doc_texts = _iter_doc_texts(project_root, config=_config_without_doc_pin(config))
    behaviors_by_doc = {
        doc: parse_vb_table(text, source_doc=doc) for doc, text in doc_texts
    }

    # Resolve the canonical doc among the discovered docs (path-based, since at
    # audit time only paths on disk are known). The declared-id universe is read
    # ONLY from that canonical doc — references never contribute declarations.
    canonical_docs = [doc for doc in behaviors_by_doc if is_canonical_vb_doc(output_path=doc)]
    canonical_doc = canonical_docs[0] if canonical_docs else None

    issues: list[VBRegistryIssue] = []

    if canonical_doc is None:
        issues.append(
            VBRegistryIssue(
                kind="missing_canonical_doc",
                severity="error",
                source_doc=_CANONICAL_VB_OUTPUT_PATH,
                message=(
                    f"No canonical verifiable-behavior registry document "
                    f"(`{_CANONICAL_VB_OUTPUT_PATH}`) was found. Exactly one document must "
                    "own the VB id namespace and declare every verifiable behavior once as a "
                    "first-column `VB-*` row; other docs reference those ids in a later column."
                ),
            )
        )
        # Without a canonical doc there is no declared universe to resolve
        # references against; reporting per-reference "unresolved" on top of the
        # missing-doc error would be noise. The missing-doc error is the signal.
        return issues

    declared_ids = {
        _normalize_vb_id(behavior.vb_id) for behavior in behaviors_by_doc.get(canonical_doc, [])
    }

    if not declared_ids:
        issues.append(
            VBRegistryIssue(
                kind="empty_canonical_registry",
                severity="error",
                source_doc=canonical_doc,
                message=(
                    f"The canonical verifiable-behavior registry (`{canonical_doc}`) declares "
                    "zero first-column `VB-*` rows. Declare every real verifiable behavior "
                    "exactly once as a first-column `VB-*` row so coverage/authenticity can "
                    "certify the system. (References to VB ids in other docs do not count — "
                    "only first-column declarations in the canonical doc do.)"
                ),
            )
        )

    # Unresolved references: a VB-* referenced in a NON-canonical doc's later
    # columns that the canonical registry does not declare. (References inside the
    # canonical doc itself are ignored — its own first-column rows are the
    # declarations; a later-column self-reference is not an external obligation.)
    seen_unresolved: set[tuple[str, str]] = set()
    for doc, text in doc_texts:
        if is_canonical_vb_doc(output_path=doc):
            continue
        for reference in parse_vb_references(text, source_doc=doc):
            normalized = _normalize_vb_id(reference.vb_id)
            if normalized in declared_ids:
                continue
            key = (doc, normalized)
            if key in seen_unresolved:
                continue
            seen_unresolved.add(key)
            issues.append(
                VBRegistryIssue(
                    kind="unresolved_reference",
                    severity="error" if strict else "warning",
                    vb_id=reference.vb_id,
                    source_doc=doc,
                    message=(
                        f"`{doc}` references verifiable behavior `{reference.vb_id}`"
                        + (f" (row `{reference.row_id}`)" if reference.row_id else "")
                        + f", but it is not declared in the canonical registry "
                        f"(`{canonical_doc}`). Declare it there as a first-column `VB-*` row "
                        "if it is a real behavior, or fix the reference if the id is wrong."
                    ),
                )
            )

    return issues


def _config_without_doc_pin(config: dict[str, Any] | None) -> dict[str, Any] | None:
    """A shallow config copy with ``test_coverage.docs`` removed.

    The ``test_coverage.docs`` pin restricts :func:`discover_vb_documents` to the
    canonical DECLARER (a coverage-audit optimization). Registry COMPLETENESS
    must scan the whole test-doc tree (also the docs that REFERENCE VB ids), so it
    discovers by directory instead. Removing only the ``docs`` key preserves every
    other config setting (doc dirs, etc.).
    """

    if not isinstance(config, dict):
        return config
    section = config.get("test_coverage")
    if not isinstance(section, dict) or "docs" not in section:
        return config
    clone = dict(config)
    clone_section = dict(section)
    clone_section.pop("docs", None)
    clone["test_coverage"] = clone_section
    return clone


def _iter_doc_texts(
    project_root: Path,
    *,
    config: dict[str, Any] | None = None,
    docs: Iterable[Path | str] | None = None,
) -> list[tuple[str, str]]:
    """Read each discovered VB doc as ``(display_path, text)`` (decode-skip safe)."""

    project_root = Path(project_root).resolve()
    out: list[tuple[str, str]] = []
    for doc_path in discover_vb_documents(project_root, config=config, docs=docs):
        try:
            text = doc_path.read_text(encoding="utf-8")
        except (OSError, UnicodeDecodeError):
            continue
        out.append((_rel_path(doc_path, project_root), text))
    return out


def discover_vb_documents(
    project_root: Path,
    *,
    config: dict[str, Any] | None = None,
    docs: Iterable[Path | str] | None = None,
) -> list[Path]:
    """Resolve the test documents to scan for VB tables.

    Priority: explicit ``docs`` argument, then ``test_coverage.docs`` from the
    project config, then auto-discovery of ``docs/test/**/*.md``.
    """

    project_root = Path(project_root).resolve()
    candidates = list(docs or ())
    if not candidates and config:
        section = config.get("test_coverage")
        if isinstance(section, dict) and isinstance(section.get("docs"), list):
            candidates = list(section["docs"])

    resolved: list[Path] = []
    if candidates:
        for item in candidates:
            # ``test_coverage.docs`` is user-controllable (codd.yaml); jail each entry
            # so an absolute/``../`` path or an in-root symlink escaping the tree is
            # dropped (escape → skip, never read/parsed as a VB-table source).
            path = resolve_project_path(project_root, item)
            if path is None:
                continue
            if path.is_file():
                resolved.append(path)
            elif path.is_dir():
                for match in sorted(path.rglob("*.md")):
                    # Re-confine each match: an in-root dir may hold a symlink whose
                    # target escapes the root.
                    confined = resolve_project_path(project_root, match)
                    if confined is not None:
                        resolved.append(confined)
        return resolved

    default_dir = project_root / _DEFAULT_VB_DOC_DIR
    if default_dir.is_dir():
        for match in sorted(default_dir.rglob("*.md")):
            confined = resolve_project_path(project_root, match)
            if confined is not None:
                resolved.append(confined)
    return resolved


def load_verifiable_behaviors(
    project_root: Path,
    *,
    config: dict[str, Any] | None = None,
    docs: Iterable[Path | str] | None = None,
) -> list[VerifiableBehavior]:
    """Load the declared VB universe, deduplicated by id (first wins)."""

    project_root = Path(project_root).resolve()
    by_id: dict[str, VerifiableBehavior] = {}
    for doc_path in discover_vb_documents(project_root, config=config, docs=docs):
        try:
            text = doc_path.read_text(encoding="utf-8")
        except (OSError, UnicodeDecodeError):
            continue
        for behavior in parse_vb_table(text, source_doc=_rel_path(doc_path, project_root)):
            by_id.setdefault(_normalize_vb_id(behavior.vb_id), behavior)
    return list(by_id.values())


def build_vb_coverage_audit(
    project_root: Path | str,
    *,
    config: dict[str, Any] | None = None,
    docs: Iterable[Path | str] | None = None,
    test_dirs: Iterable[Path | str] | None = None,
) -> VBAuditReport:
    """Build a VB coverage audit reconciling VB tables against test markers."""

    project_root = Path(project_root).resolve()
    if config is None:
        config = _load_optional_config(project_root)
    if test_dirs is None:
        test_dirs = _resolve_vb_scan_dirs(project_root, config)

    behaviors = load_verifiable_behaviors(project_root, config=config, docs=docs)
    covers, blockers, dod_markers = _scan_vb_markers(project_root, test_dirs=test_dirs)

    declared_ids = {_normalize_vb_id(behavior.vb_id) for behavior in behaviors}
    rows = [_audit_behavior(behavior, covers, blockers) for behavior in behaviors]
    orphans = _detect_orphan_vb_markers(declared_ids, covers, blockers, dod_markers)

    covered = sum(1 for row in rows if row.coverage_status == "covered")
    blocked = sum(1 for row in rows if row.coverage_status == "blocked")
    uncovered = sum(1 for row in rows if row.coverage_status == "uncovered")
    summary: dict[str, int | str] = {
        "vb_count": len(rows),
        "covered": covered,
        "blocked": blocked,
        "uncovered": uncovered,
        "orphan_vb_markers": len(orphans),
    }
    return VBAuditReport(
        version=VB_AUDIT_CONTRACT_VERSION,
        summary=summary,
        rows=rows,
        orphan_vb_markers=orphans,
    )


def write_vb_coverage_audit(
    report: VBAuditReport,
    output_path: Path | str,
    *,
    output_format: str = "md",
) -> Path:
    """Write a VB coverage audit report as Markdown or JSON."""

    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    if output_format == "json":
        output_path.write_text(
            json.dumps(asdict(report), indent=2, ensure_ascii=False) + "\n", encoding="utf-8"
        )
    elif output_format == "md":
        output_path.write_text(render_vb_coverage_audit_markdown(report), encoding="utf-8")
    else:
        raise ValueError(f"Unsupported verifiable-behavior audit format: {output_format}")
    return output_path


def render_vb_coverage_audit_markdown(report: VBAuditReport) -> str:
    """Render the VB coverage audit report as Markdown."""

    lines = [
        "# Verifiable Behavior Coverage Audit",
        "",
        f"- Contract: {report.version}",
        f"- Verifiable behaviors: {report.summary['vb_count']}",
        f"- Covered by `codd: covers vb=` marker: {report.summary['covered']}",
        f"- Blocked by explicit blocker marker: {report.summary['blocked']}",
        f"- Uncovered: {report.summary['uncovered']}",
        f"- Orphan vb markers: {report.summary['orphan_vb_markers']}",
        "",
        "## Behavior Matrix",
        "| VB | Description | Source Doc | Status | Evidence | Next Action |",
        "| --- | --- | --- | --- | --- | --- |",
    ]
    for row in report.rows:
        evidence = ", ".join(row.matched_tests) if row.matched_tests else ""
        if row.blocker_evidence:
            blocker_text = f"blocker: {row.blocker_reason}"
            if row.blocker_details:
                blocker_text += f" ({row.blocker_details})"
            blocker = ", ".join(row.blocker_evidence)
            evidence = f"{evidence}; {blocker_text}: {blocker}" if evidence else f"{blocker_text}: {blocker}"
        lines.append(
            "| "
            + " | ".join(
                [
                    _md_cell(row.vb_id),
                    _md_cell(row.description),
                    _md_cell(row.source_doc),
                    _md_cell(row.coverage_status),
                    _md_cell(evidence or "-"),
                    _md_cell(row.suggested_next_action),
                ]
            )
            + " |"
        )
    if report.orphan_vb_markers:
        lines.extend(
            [
                "",
                "## Orphan VB Markers",
                "These markers reference a VB id that no test document declares; "
                "declare the behavior or fix the marker.",
                "",
                "| Test | VB | Marker |",
                "| --- | --- | --- |",
            ]
        )
        for orphan in report.orphan_vb_markers:
            lines.append(
                "| "
                + " | ".join([_md_cell(orphan.path), _md_cell(orphan.vb_id), _md_cell(orphan.marker_kind)])
                + " |"
            )
    lines.append("")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Implement coverage gate helpers
# ---------------------------------------------------------------------------


def coverage_gate_enabled(config: dict[str, Any] | None) -> bool:
    """Whether the implement-completion coverage gate is enabled (default ON)."""

    section = (config or {}).get("test_coverage")
    if isinstance(section, dict) and "gate" in section:
        return bool(section["gate"])
    return True


def coverage_gate_max_retries(config: dict[str, Any] | None) -> int:
    """Bounded re-implementation attempts before the gate fails (default 2)."""

    section = (config or {}).get("test_coverage")
    if isinstance(section, dict):
        value = section.get("max_retries")
        if isinstance(value, int) and value >= 0:
            return value
    return 2


def is_test_related_implement(
    config: dict[str, Any] | None,
    *,
    design_node: str | None,
    output_paths: Iterable[str],
) -> bool:
    """Whether an implement run targets test artifacts.

    True when any output path lives under a configured ``scan.test_dirs``
    entry (or carries a ``.spec.``/``.test.`` style filename), or the design
    node is a test-type document (``test:`` node id or a path under the
    ``docs/test`` doc-type directory).
    """

    if design_node:
        normalized = design_node.strip().replace("\\", "/")
        if normalized.startswith("test:"):
            return True
        parts = PurePosixPath(normalized).parts
        if len(parts) >= 3 and parts[0] == "docs" and parts[1] == "test":
            return True

    raw_dirs = ((config or {}).get("scan") or {}).get("test_dirs")
    test_dirs = [str(item) for item in raw_dirs] if isinstance(raw_dirs, list) and raw_dirs else ["tests/"]
    prefixes = [item.replace("\\", "/").strip("/") for item in test_dirs if str(item).strip("/")]
    for raw_path in output_paths:
        rel = str(raw_path).replace("\\", "/").strip("/")
        if not rel:
            continue
        for prefix in prefixes:
            if rel == prefix or rel.startswith(prefix + "/"):
                return True
        name = PurePosixPath(rel).name
        if re.search(r"\.(spec|test|e2e)\.[A-Za-z0-9]+$", name):
            return True
    return False


def format_gap_feedback(report: VBAuditReport) -> str:
    """Render uncovered VBs as review feedback for a bounded re-implementation."""

    lines = [
        "The generated tests do not cover every declared verifiable behavior.",
        "For EACH behavior listed below, add (or extend) a test that proves it and "
        "annotate that test with a comment marker of the exact form "
        "`codd: covers vb=<ID>` (one marker per behavior, placed inside the test file).",
        # Anti-false-coverage: a covers marker is a CLAIM that the test proves the
        # behavior; "add a marker" must never be satisfied by marking an empty or
        # skipped test (the marker-authenticity gate will reject that).
        "Do not add `codd: covers vb=X` to an existing test unless that test exercises the "
        "public behavior described by X and contains assertions that would FAIL if X were "
        "broken. If no such test exists, create or extend a real test FIRST, then mark it.",
        "If a behavior genuinely cannot be tested yet, add an explicit "
        "`codd: blocked vb=<ID> reason=<short_reason>` marker instead — never leave it silently uncovered.",
        "",
        "Uncovered verifiable behaviors:",
    ]
    for row in report.uncovered_rows:
        description = f" — {row.description}" if row.description else ""
        lines.append(f"- {row.vb_id}{description} (declared in {row.source_doc})")
    return "\n".join(lines)


def run_implement_coverage_gate(
    project_root: Path | str,
    *,
    config: dict[str, Any] | None = None,
    design_node: str | None,
    output_paths: Iterable[str],
    opt_out: bool = False,
    rerun: Callable[[str], None] | None = None,
    echo: Callable[[str], None] = print,
    echo_error: Callable[[str], None] | None = None,
) -> bool:
    """Audit VB coverage after an implement run; retry with feedback, then gate.

    Returns ``True`` when the gate passes (or does not apply) and ``False``
    when uncovered VBs remain after the bounded retries. Projects without any
    VB table are unaffected: the gate announces that and passes.
    """

    project_root = Path(project_root).resolve()
    if config is None:
        config = _load_optional_config(project_root)
    if opt_out or not coverage_gate_enabled(config):
        return True
    if not is_test_related_implement(config, design_node=design_node, output_paths=output_paths):
        return True

    emit_error = echo_error or echo
    report = build_vb_coverage_audit(project_root, config=config)
    if not report.rows:
        echo("Test coverage gate: no VB table found in test documents — nothing to audit.")
        return True

    max_retries = coverage_gate_max_retries(config)
    attempt = 0
    while report.uncovered_rows and rerun is not None and attempt < max_retries:
        attempt += 1
        echo(
            f"Test coverage gate: {len(report.uncovered_rows)} uncovered verifiable behavior(s); "
            f"re-running implementation with gap feedback (attempt {attempt}/{max_retries})"
        )
        rerun(format_gap_feedback(report))
        report = build_vb_coverage_audit(project_root, config=config)

    for orphan in report.orphan_vb_markers:
        emit_error(orphan.message)
    if report.uncovered_rows:
        emit_error(
            f"Test coverage gate FAILED: {len(report.uncovered_rows)} of {report.summary['vb_count']} "
            "verifiable behavior(s) have no `codd: covers vb=` marker:"
        )
        for row in report.uncovered_rows:
            description = f" — {row.description}" if row.description else ""
            emit_error(f"  ✗ {row.vb_id}{description} ({row.source_doc})")
        emit_error(
            "Add a covering test with a `codd: covers vb=<ID>` marker, declare an explicit "
            "`codd: blocked vb=<ID> reason=...` marker, or opt out with --no-coverage-gate."
        )
        return False

    echo(
        f"Test coverage gate: {report.summary['covered']} covered / "
        f"{report.summary['blocked']} blocked / {report.summary['vb_count']} verifiable behavior(s) — OK"
    )
    return True


# ---------------------------------------------------------------------------
# Internals
# ---------------------------------------------------------------------------



def _scan_vb_markers(
    project_root: Path,
    *,
    test_dirs: Iterable[Path | str] | None,
) -> tuple[list[VBCoverEvidence], list[VBBlockerEvidence], list[tuple[str, str]]]:
    covers: list[VBCoverEvidence] = []
    blockers: list[VBBlockerEvidence] = []
    dod_markers: list[tuple[str, str]] = []  # (path, vb_id)
    for path in _iter_test_files(project_root, test_dirs=test_dirs):
        try:
            text = path.read_text(encoding="utf-8")
        except (OSError, UnicodeDecodeError):
            continue
        rel_path = _rel_path(path, project_root)
        for match in _COVER_MARKER_RE.finditer(text):
            first_vb = match.group("vb")
            if first_vb is None:
                continue  # operation-subject marker; owned by the operational audit
            # A single covers marker may list several `vb=` ids on one line
            # (`# codd: covers vb=22 vb=23 vb=24`): the shared regex captures
            # only the first and its greedy details group swallows the rest.
            # Recover every id, treating the non-`vb=` remainder as shared
            # details so all of them are reconciled, not just the first.
            raw_details = match.group("details") or ""
            extra_ids = [token.group("vb").strip() for token in _VB_TOKEN_RE.finditer(raw_details)]
            details = _VB_TOKEN_RE.sub("", raw_details).strip()
            for vb_id in [first_vb.strip(), *extra_ids]:
                covers.append(
                    VBCoverEvidence(
                        path=rel_path,
                        vb_id=vb_id,
                        details=details,
                    )
                )
        for match in _BLOCKER_MARKER_RE.finditer(text):
            vb_id = match.group("vb")
            if vb_id is None:
                continue
            blockers.append(
                VBBlockerEvidence(
                    path=rel_path,
                    vb_id=vb_id.strip(),
                    reason=match.group("reason").strip(),
                    details=(match.group("details") or "").strip(),
                )
            )
        for match in _DOD_MARKER_RE.finditer(text):
            vb_id = match.group("vb")
            if vb_id is None:
                continue
            dod_markers.append((rel_path, vb_id.strip()))
    return covers, blockers, dod_markers


def _audit_behavior(
    behavior: VerifiableBehavior,
    covers: list[VBCoverEvidence],
    blockers: list[VBBlockerEvidence],
) -> VBAuditRow:
    normalized = _normalize_vb_id(behavior.vb_id)
    matched = sorted({item.path for item in covers if _normalize_vb_id(item.vb_id) == normalized})
    matching_blockers = [item for item in blockers if _normalize_vb_id(item.vb_id) == normalized]
    primary_blocker = matching_blockers[0] if matching_blockers else None

    if primary_blocker is not None:
        status = "blocked"
        next_action = (
            "Resolve the explicit blocker, then replace the blocker marker with a covers marker."
        )
    elif matched:
        status = "covered"
        next_action = "Run the covering test(s) and keep the marker in sync on refactor."
    else:
        status = "uncovered"
        next_action = "Create or extend a test with a `codd: covers vb=` marker."

    return VBAuditRow(
        vb_id=behavior.vb_id,
        description=behavior.description,
        source_doc=behavior.source_doc,
        coverage_status=status,
        matched_tests=matched,
        blocker_reason=primary_blocker.reason if primary_blocker else "",
        blocker_details=primary_blocker.details if primary_blocker else "",
        blocker_evidence=sorted({item.path for item in matching_blockers}),
        suggested_next_action=next_action,
    )


def _detect_orphan_vb_markers(
    declared_ids: set[str],
    covers: list[VBCoverEvidence],
    blockers: list[VBBlockerEvidence],
    dod_markers: list[tuple[str, str]],
) -> list[OrphanVBMarker]:
    orphans: list[OrphanVBMarker] = []
    seen: set[tuple[str, str, str]] = set()

    def _check(path: str, vb_id: str, marker_kind: str) -> None:
        if _normalize_vb_id(vb_id) in declared_ids:
            return
        key = (path, _normalize_vb_id(vb_id), marker_kind)
        if key in seen:
            return
        seen.add(key)
        orphans.append(OrphanVBMarker(path=path, vb_id=vb_id, marker_kind=marker_kind))

    for item in covers:
        _check(item.path, item.vb_id, "covers")
    for blocker in blockers:
        _check(blocker.path, blocker.vb_id, "blocked")
    for path, vb_id in dod_markers:
        _check(path, vb_id, "dod")
    return orphans


# A leading ``vb`` is only stripped when it is a standalone token — i.e. the
# very next character is an id separator (``-``/``_``/``=``/space) or the value
# ends there. This makes the rule symmetric: ``VB-08`` and a bare marker value
# ``08`` converge, while a body that genuinely begins with ``vb`` (e.g.
# ``VB-vbx`` vs marker ``vbx``) is preserved on both sides instead of being
# eaten asymmetrically.
_LEADING_VB_TOKEN_RE = re.compile(r"^vb(?=[-_= \t]|$)")
_LEADING_SEPARATORS = "-_= \t"


def _normalize_vb_id(value: str) -> str:
    """Canonical matching key for a verifiable-behavior id.

    Declared ids (``VB-08``) and marker values (``vb=08`` → captured ``08``,
    or ``vb=VB-08`` → captured ``VB-08``) must reconcile to the same key. The
    canonical rule:

    1. casefold and strip surrounding whitespace,
    2. drop a single leading ``vb`` token (only when it stands alone, followed
       by a separator or end) plus any leading separators (``-``/``_``/``=``/
       space), so ``vb-08`` and bare ``08`` converge,
    3. for a purely-numeric remainder, strip leading zeros (``08`` → ``8``)
       so zero-padding never changes identity — while keeping distinct numbers
       distinct (``1`` stays ``1``, ``11`` stays ``11``: no collision),
    4. keep non-numeric remainders as-is (so schemes like ``VB-AUTH-1`` →
       ``auth-1`` still work).

    A value that reduces to nothing (e.g. a bare ``VB``) falls back to its
    casefolded form so it never collides with a genuinely empty key.
    """

    base = value.strip().casefold()
    remainder = _LEADING_VB_TOKEN_RE.sub("", base, count=1).lstrip(_LEADING_SEPARATORS)
    if not remainder:
        return base
    if remainder.isdigit():
        return remainder.lstrip("0") or "0"
    return remainder
