"""Verifiable-behavior (VB) coverage audit.

Test documents generated by ``codd generate`` declare a design-to-test
traceability table whose first column is a stable ``VB-<id>`` identifier, one
row per verifiable behavior. This module reconciles that declared universe
against ``codd: covers vb=<id>`` markers in test code, mirroring the
operational E2E audit semantics (explicit covers markers, explicit blockers,
orphan-marker reverse reconciliation).

The parser is header-text independent: any Markdown table whose first cell is
a ``VB-`` style id is a traceability row, so Japanese/English/any-language
headers all work. The marker grammar is shared with
``codd.operational_e2e_audit`` (subject alternation ``operation=``/``vb=``).
"""

from __future__ import annotations

import json
import re
from dataclasses import asdict, dataclass, field
from pathlib import Path, PurePosixPath
from typing import Any, Callable, Iterable

from codd.operational_e2e_audit import (
    _BLOCKER_MARKER_RE,
    _COVER_MARKER_RE,
    _DOD_MARKER_RE,
    _iter_test_files,
    _md_cell,
    _rel_path,
)

VB_AUDIT_CONTRACT_VERSION = "verifiable-behavior-audit/v1"

# First-cell id pattern: `VB-` followed by an alphanumeric id body. Header
# rows ("#", "ID", "検証可能ビヘイビア", ...) and separator rows never match.
_VB_ID_RE = re.compile(r"^VB-[A-Za-z0-9][A-Za-z0-9_.-]*$", re.IGNORECASE)
_TABLE_ROW_RE = re.compile(r"^\s*\|(?P<cells>.+)\|\s*$")
_FENCE_RE = re.compile(r"^\s*(```|~~~)")
_DEFAULT_VB_DOC_DIR = "docs/test"


@dataclass(frozen=True)
class VerifiableBehavior:
    """One declared verifiable behavior from a test-document VB table."""

    vb_id: str
    description: str
    source_doc: str
    declared_scenarios: str = ""


@dataclass(frozen=True)
class VBCoverEvidence:
    """A ``codd: covers vb=<id>`` claim found in a test file."""

    path: str
    vb_id: str
    details: str = ""


@dataclass(frozen=True)
class VBBlockerEvidence:
    """A ``codd: blocked vb=<id> reason=<reason>`` claim found in a test file."""

    path: str
    vb_id: str
    reason: str
    details: str = ""


@dataclass(frozen=True)
class OrphanVBMarker:
    """A vb-subject marker whose VB id is declared in no VB table."""

    path: str
    vb_id: str
    marker_kind: str  # covers / blocked / dod

    @property
    def message(self) -> str:
        return (
            f"[orphan_vb_marker] Test `{self.path}` claims `codd: {self.marker_kind} "
            f"vb={self.vb_id}`, but no test document declares `{self.vb_id}` in a "
            f"VB traceability table. Declare the behavior in the test document or "
            f"fix the marker if the id is wrong/renamed."
        )


@dataclass
class VBAuditRow:
    """Audit row for one declared verifiable behavior."""

    vb_id: str
    description: str
    source_doc: str
    coverage_status: str  # covered / blocked / uncovered
    matched_tests: list[str] = field(default_factory=list)
    blocker_reason: str = ""
    blocker_details: str = ""
    blocker_evidence: list[str] = field(default_factory=list)
    suggested_next_action: str = ""


@dataclass
class VBAuditReport:
    """Serializable verifiable-behavior coverage audit report."""

    version: str
    summary: dict[str, int | str]
    rows: list[VBAuditRow]
    orphan_vb_markers: list[OrphanVBMarker] = field(default_factory=list)

    @property
    def uncovered_rows(self) -> list[VBAuditRow]:
        return [row for row in self.rows if row.coverage_status == "uncovered"]


def parse_vb_table(markdown_text: str, *, source_doc: str = "") -> list[VerifiableBehavior]:
    """Extract VB rows from Markdown text, ignoring header wording entirely.

    A row qualifies when its first cell (after stripping inline formatting) is
    a ``VB-<id>``. Fenced code blocks are skipped so examples never count.
    """

    behaviors: list[VerifiableBehavior] = []
    in_fence = False
    for line in markdown_text.splitlines():
        if _FENCE_RE.match(line):
            in_fence = not in_fence
            continue
        if in_fence:
            continue
        match = _TABLE_ROW_RE.match(line)
        if not match:
            continue
        cells = [cell.strip() for cell in match.group("cells").split("|")]
        if not cells:
            continue
        first = cells[0].strip("`*_ ").strip()
        if not _VB_ID_RE.match(first):
            continue
        behaviors.append(
            VerifiableBehavior(
                vb_id=first,
                description=cells[1] if len(cells) > 1 else "",
                source_doc=source_doc,
                declared_scenarios=" | ".join(cells[2:]) if len(cells) > 2 else "",
            )
        )
    return behaviors


def discover_vb_documents(
    project_root: Path,
    *,
    config: dict[str, Any] | None = None,
    docs: Iterable[Path | str] | None = None,
) -> list[Path]:
    """Resolve the test documents to scan for VB tables.

    Priority: explicit ``docs`` argument, then ``test_coverage.docs`` from the
    project config, then auto-discovery of ``docs/test/**/*.md``.
    """

    project_root = Path(project_root).resolve()
    candidates = list(docs or ())
    if not candidates and config:
        section = config.get("test_coverage")
        if isinstance(section, dict) and isinstance(section.get("docs"), list):
            candidates = list(section["docs"])

    resolved: list[Path] = []
    if candidates:
        for item in candidates:
            path = Path(item)
            if not path.is_absolute():
                path = project_root / path
            if path.is_file():
                resolved.append(path)
            elif path.is_dir():
                resolved.extend(sorted(path.rglob("*.md")))
        return resolved

    default_dir = project_root / _DEFAULT_VB_DOC_DIR
    if default_dir.is_dir():
        resolved.extend(sorted(default_dir.rglob("*.md")))
    return resolved


def load_verifiable_behaviors(
    project_root: Path,
    *,
    config: dict[str, Any] | None = None,
    docs: Iterable[Path | str] | None = None,
) -> list[VerifiableBehavior]:
    """Load the declared VB universe, deduplicated by id (first wins)."""

    project_root = Path(project_root).resolve()
    by_id: dict[str, VerifiableBehavior] = {}
    for doc_path in discover_vb_documents(project_root, config=config, docs=docs):
        try:
            text = doc_path.read_text(encoding="utf-8")
        except (OSError, UnicodeDecodeError):
            continue
        for behavior in parse_vb_table(text, source_doc=_rel_path(doc_path, project_root)):
            by_id.setdefault(_normalize_vb_id(behavior.vb_id), behavior)
    return list(by_id.values())


def build_vb_coverage_audit(
    project_root: Path | str,
    *,
    config: dict[str, Any] | None = None,
    docs: Iterable[Path | str] | None = None,
    test_dirs: Iterable[Path | str] | None = None,
) -> VBAuditReport:
    """Build a VB coverage audit reconciling VB tables against test markers."""

    project_root = Path(project_root).resolve()
    if config is None:
        config = _load_optional_config(project_root)
    if test_dirs is None:
        configured_test_dirs = (config.get("scan") or {}).get("test_dirs")
        if isinstance(configured_test_dirs, list) and configured_test_dirs:
            test_dirs = configured_test_dirs

    behaviors = load_verifiable_behaviors(project_root, config=config, docs=docs)
    covers, blockers, dod_markers = _scan_vb_markers(project_root, test_dirs=test_dirs)

    declared_ids = {_normalize_vb_id(behavior.vb_id) for behavior in behaviors}
    rows = [_audit_behavior(behavior, covers, blockers) for behavior in behaviors]
    orphans = _detect_orphan_vb_markers(declared_ids, covers, blockers, dod_markers)

    covered = sum(1 for row in rows if row.coverage_status == "covered")
    blocked = sum(1 for row in rows if row.coverage_status == "blocked")
    uncovered = sum(1 for row in rows if row.coverage_status == "uncovered")
    summary: dict[str, int | str] = {
        "vb_count": len(rows),
        "covered": covered,
        "blocked": blocked,
        "uncovered": uncovered,
        "orphan_vb_markers": len(orphans),
    }
    return VBAuditReport(
        version=VB_AUDIT_CONTRACT_VERSION,
        summary=summary,
        rows=rows,
        orphan_vb_markers=orphans,
    )


def write_vb_coverage_audit(
    report: VBAuditReport,
    output_path: Path | str,
    *,
    output_format: str = "md",
) -> Path:
    """Write a VB coverage audit report as Markdown or JSON."""

    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    if output_format == "json":
        output_path.write_text(
            json.dumps(asdict(report), indent=2, ensure_ascii=False) + "\n", encoding="utf-8"
        )
    elif output_format == "md":
        output_path.write_text(render_vb_coverage_audit_markdown(report), encoding="utf-8")
    else:
        raise ValueError(f"Unsupported verifiable-behavior audit format: {output_format}")
    return output_path


def render_vb_coverage_audit_markdown(report: VBAuditReport) -> str:
    """Render the VB coverage audit report as Markdown."""

    lines = [
        "# Verifiable Behavior Coverage Audit",
        "",
        f"- Contract: {report.version}",
        f"- Verifiable behaviors: {report.summary['vb_count']}",
        f"- Covered by `codd: covers vb=` marker: {report.summary['covered']}",
        f"- Blocked by explicit blocker marker: {report.summary['blocked']}",
        f"- Uncovered: {report.summary['uncovered']}",
        f"- Orphan vb markers: {report.summary['orphan_vb_markers']}",
        "",
        "## Behavior Matrix",
        "| VB | Description | Source Doc | Status | Evidence | Next Action |",
        "| --- | --- | --- | --- | --- | --- |",
    ]
    for row in report.rows:
        evidence = ", ".join(row.matched_tests) if row.matched_tests else ""
        if row.blocker_evidence:
            blocker_text = f"blocker: {row.blocker_reason}"
            if row.blocker_details:
                blocker_text += f" ({row.blocker_details})"
            blocker = ", ".join(row.blocker_evidence)
            evidence = f"{evidence}; {blocker_text}: {blocker}" if evidence else f"{blocker_text}: {blocker}"
        lines.append(
            "| "
            + " | ".join(
                [
                    _md_cell(row.vb_id),
                    _md_cell(row.description),
                    _md_cell(row.source_doc),
                    _md_cell(row.coverage_status),
                    _md_cell(evidence or "-"),
                    _md_cell(row.suggested_next_action),
                ]
            )
            + " |"
        )
    if report.orphan_vb_markers:
        lines.extend(
            [
                "",
                "## Orphan VB Markers",
                "These markers reference a VB id that no test document declares; "
                "declare the behavior or fix the marker.",
                "",
                "| Test | VB | Marker |",
                "| --- | --- | --- |",
            ]
        )
        for orphan in report.orphan_vb_markers:
            lines.append(
                "| "
                + " | ".join([_md_cell(orphan.path), _md_cell(orphan.vb_id), _md_cell(orphan.marker_kind)])
                + " |"
            )
    lines.append("")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Implement coverage gate helpers
# ---------------------------------------------------------------------------


def coverage_gate_enabled(config: dict[str, Any] | None) -> bool:
    """Whether the implement-completion coverage gate is enabled (default ON)."""

    section = (config or {}).get("test_coverage")
    if isinstance(section, dict) and "gate" in section:
        return bool(section["gate"])
    return True


def coverage_gate_max_retries(config: dict[str, Any] | None) -> int:
    """Bounded re-implementation attempts before the gate fails (default 2)."""

    section = (config or {}).get("test_coverage")
    if isinstance(section, dict):
        value = section.get("max_retries")
        if isinstance(value, int) and value >= 0:
            return value
    return 2


def is_test_related_implement(
    config: dict[str, Any] | None,
    *,
    design_node: str | None,
    output_paths: Iterable[str],
) -> bool:
    """Whether an implement run targets test artifacts.

    True when any output path lives under a configured ``scan.test_dirs``
    entry (or carries a ``.spec.``/``.test.`` style filename), or the design
    node is a test-type document (``test:`` node id or a path under the
    ``docs/test`` doc-type directory).
    """

    if design_node:
        normalized = design_node.strip().replace("\\", "/")
        if normalized.startswith("test:"):
            return True
        parts = PurePosixPath(normalized).parts
        if len(parts) >= 3 and parts[0] == "docs" and parts[1] == "test":
            return True

    raw_dirs = ((config or {}).get("scan") or {}).get("test_dirs")
    test_dirs = [str(item) for item in raw_dirs] if isinstance(raw_dirs, list) and raw_dirs else ["tests/"]
    prefixes = [item.replace("\\", "/").strip("/") for item in test_dirs if str(item).strip("/")]
    for raw_path in output_paths:
        rel = str(raw_path).replace("\\", "/").strip("/")
        if not rel:
            continue
        for prefix in prefixes:
            if rel == prefix or rel.startswith(prefix + "/"):
                return True
        name = PurePosixPath(rel).name
        if re.search(r"\.(spec|test)\.[A-Za-z0-9]+$", name):
            return True
    return False


def format_gap_feedback(report: VBAuditReport) -> str:
    """Render uncovered VBs as review feedback for a bounded re-implementation."""

    lines = [
        "The generated tests do not cover every declared verifiable behavior.",
        "For EACH behavior listed below, add (or extend) a test that proves it and "
        "annotate that test with a comment marker of the exact form "
        "`codd: covers vb=<ID>` (one marker per behavior, placed inside the test file).",
        "If a behavior genuinely cannot be tested yet, add an explicit "
        "`codd: blocked vb=<ID> reason=<short_reason>` marker instead — never leave it silently uncovered.",
        "",
        "Uncovered verifiable behaviors:",
    ]
    for row in report.uncovered_rows:
        description = f" — {row.description}" if row.description else ""
        lines.append(f"- {row.vb_id}{description} (declared in {row.source_doc})")
    return "\n".join(lines)


def run_implement_coverage_gate(
    project_root: Path | str,
    *,
    config: dict[str, Any] | None = None,
    design_node: str | None,
    output_paths: Iterable[str],
    opt_out: bool = False,
    rerun: Callable[[str], None] | None = None,
    echo: Callable[[str], None] = print,
    echo_error: Callable[[str], None] | None = None,
) -> bool:
    """Audit VB coverage after an implement run; retry with feedback, then gate.

    Returns ``True`` when the gate passes (or does not apply) and ``False``
    when uncovered VBs remain after the bounded retries. Projects without any
    VB table are unaffected: the gate announces that and passes.
    """

    project_root = Path(project_root).resolve()
    if config is None:
        config = _load_optional_config(project_root)
    if opt_out or not coverage_gate_enabled(config):
        return True
    if not is_test_related_implement(config, design_node=design_node, output_paths=output_paths):
        return True

    emit_error = echo_error or echo
    report = build_vb_coverage_audit(project_root, config=config)
    if not report.rows:
        echo("Test coverage gate: no VB table found in test documents — nothing to audit.")
        return True

    max_retries = coverage_gate_max_retries(config)
    attempt = 0
    while report.uncovered_rows and rerun is not None and attempt < max_retries:
        attempt += 1
        echo(
            f"Test coverage gate: {len(report.uncovered_rows)} uncovered verifiable behavior(s); "
            f"re-running implementation with gap feedback (attempt {attempt}/{max_retries})"
        )
        rerun(format_gap_feedback(report))
        report = build_vb_coverage_audit(project_root, config=config)

    for orphan in report.orphan_vb_markers:
        emit_error(orphan.message)
    if report.uncovered_rows:
        emit_error(
            f"Test coverage gate FAILED: {len(report.uncovered_rows)} of {report.summary['vb_count']} "
            "verifiable behavior(s) have no `codd: covers vb=` marker:"
        )
        for row in report.uncovered_rows:
            description = f" — {row.description}" if row.description else ""
            emit_error(f"  ✗ {row.vb_id}{description} ({row.source_doc})")
        emit_error(
            "Add a covering test with a `codd: covers vb=<ID>` marker, declare an explicit "
            "`codd: blocked vb=<ID> reason=...` marker, or opt out with --no-coverage-gate."
        )
        return False

    echo(
        f"Test coverage gate: {report.summary['covered']} covered / "
        f"{report.summary['blocked']} blocked / {report.summary['vb_count']} verifiable behavior(s) — OK"
    )
    return True


# ---------------------------------------------------------------------------
# Internals
# ---------------------------------------------------------------------------


def _load_optional_config(project_root: Path) -> dict[str, Any]:
    from codd.config import load_project_config

    try:
        return load_project_config(project_root)
    except (FileNotFoundError, ValueError):
        return {}


def _scan_vb_markers(
    project_root: Path,
    *,
    test_dirs: Iterable[Path | str] | None,
) -> tuple[list[VBCoverEvidence], list[VBBlockerEvidence], list[tuple[str, str]]]:
    covers: list[VBCoverEvidence] = []
    blockers: list[VBBlockerEvidence] = []
    dod_markers: list[tuple[str, str]] = []  # (path, vb_id)
    for path in _iter_test_files(project_root, test_dirs=test_dirs):
        try:
            text = path.read_text(encoding="utf-8")
        except (OSError, UnicodeDecodeError):
            continue
        rel_path = _rel_path(path, project_root)
        for match in _COVER_MARKER_RE.finditer(text):
            vb_id = match.group("vb")
            if vb_id is None:
                continue  # operation-subject marker; owned by the operational audit
            covers.append(
                VBCoverEvidence(
                    path=rel_path,
                    vb_id=vb_id.strip(),
                    details=(match.group("details") or "").strip(),
                )
            )
        for match in _BLOCKER_MARKER_RE.finditer(text):
            vb_id = match.group("vb")
            if vb_id is None:
                continue
            blockers.append(
                VBBlockerEvidence(
                    path=rel_path,
                    vb_id=vb_id.strip(),
                    reason=match.group("reason").strip(),
                    details=(match.group("details") or "").strip(),
                )
            )
        for match in _DOD_MARKER_RE.finditer(text):
            vb_id = match.group("vb")
            if vb_id is None:
                continue
            dod_markers.append((rel_path, vb_id.strip()))
    return covers, blockers, dod_markers


def _audit_behavior(
    behavior: VerifiableBehavior,
    covers: list[VBCoverEvidence],
    blockers: list[VBBlockerEvidence],
) -> VBAuditRow:
    normalized = _normalize_vb_id(behavior.vb_id)
    matched = sorted({item.path for item in covers if _normalize_vb_id(item.vb_id) == normalized})
    matching_blockers = [item for item in blockers if _normalize_vb_id(item.vb_id) == normalized]
    primary_blocker = matching_blockers[0] if matching_blockers else None

    if primary_blocker is not None:
        status = "blocked"
        next_action = (
            "Resolve the explicit blocker, then replace the blocker marker with a covers marker."
        )
    elif matched:
        status = "covered"
        next_action = "Run the covering test(s) and keep the marker in sync on refactor."
    else:
        status = "uncovered"
        next_action = "Create or extend a test with a `codd: covers vb=` marker."

    return VBAuditRow(
        vb_id=behavior.vb_id,
        description=behavior.description,
        source_doc=behavior.source_doc,
        coverage_status=status,
        matched_tests=matched,
        blocker_reason=primary_blocker.reason if primary_blocker else "",
        blocker_details=primary_blocker.details if primary_blocker else "",
        blocker_evidence=sorted({item.path for item in matching_blockers}),
        suggested_next_action=next_action,
    )


def _detect_orphan_vb_markers(
    declared_ids: set[str],
    covers: list[VBCoverEvidence],
    blockers: list[VBBlockerEvidence],
    dod_markers: list[tuple[str, str]],
) -> list[OrphanVBMarker]:
    orphans: list[OrphanVBMarker] = []
    seen: set[tuple[str, str, str]] = set()

    def _check(path: str, vb_id: str, marker_kind: str) -> None:
        if _normalize_vb_id(vb_id) in declared_ids:
            return
        key = (path, _normalize_vb_id(vb_id), marker_kind)
        if key in seen:
            return
        seen.add(key)
        orphans.append(OrphanVBMarker(path=path, vb_id=vb_id, marker_kind=marker_kind))

    for item in covers:
        _check(item.path, item.vb_id, "covers")
    for blocker in blockers:
        _check(blocker.path, blocker.vb_id, "blocked")
    for path, vb_id in dod_markers:
        _check(path, vb_id, "dod")
    return orphans


def _normalize_vb_id(value: str) -> str:
    return value.strip().casefold()
