"""Impact planning for ``codd fix [PHENOMENON]`` (Stage 4 target resolution).

The legacy Stage-4 path resolves implementation files by walking *forward*
``expects`` edges from the chosen design node, with a coarse frontmatter
``modules`` glob fallback. In a brownfield codebase whose design docs link only
at MODULE granularity, that resolves 0–1 files and the propagation silently
under-reaches — a multi-surface feature (an entity touched across a create
API, an update API, an end-user render surface, and an admin input surface)
only gets one surface patched, which is a *semantic false green*.

This module replaces "follow existing links" with "DISCOVER the change
surface, then PROVE each candidate by evidence":

    phenomenon analysis
      → impact obligations (LLM-proposed OR deterministic baseline)
      → candidate gathering (DAG-exact, module fallback, code search, graph
        neighbors, tests)
      → evidence scoring (hard sources auto-accept; soft evidence needs
        independent corroboration)
      → obligation coverage check
      → status: complete | incomplete | ambiguous

Cardinal rules honored here:

* **anti-false-green** — incomplete or ambiguous resolution is NEVER silently
  downgraded to a partial apply. The planner returns a non-``complete`` status
  with an explicit reason; the caller fail-fasts.
* **generality** — no project or framework names. Only path tokens, content
  tokens, DAG edges, and import/test graph structure. The LLM only *proposes*
  terms and obligations; deterministic evidence decides the allowlist, the
  coverage, and the status.
* **model-agnostic** — works with an empty LLM decomposition via the
  deterministic baseline obligation derivation.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Iterable, Literal

from codd.dag.impact import (
    affected_impl_targets,
    find_impl_candidates,
    find_impl_candidates_v2,
    is_test_path,
    normalize_terms,
)
from codd.fix.phenomenon_parser import PhenomenonAnalysis

# Evidence sources that are, on their own, sufficient to accept a candidate.
# These are deterministic graph facts (a design doc declared the file, or the
# lexicon extraction resolved to it), not a fuzzy text match.
HARD_SOURCES = frozenset({"expects", "expected_extraction"})

# ``content_token`` is the weakest evidence (a single bare term appears in the
# file) and must NEVER count toward the "independent corroboration" requirement
# on its own — otherwise one common word would admit half the repo.
_NON_INDEPENDENT_SOURCES = frozenset({"content_token"})

# Default soft-acceptance thresholds (overridable by the caller).
_DEFAULT_MIN_SCORE = 0.55
_DEFAULT_MIN_INDEPENDENT_SOURCES = 2
_DEFAULT_MAX_IMPL_CANDIDATES = 12

# Evidence weights. Path equality is the strongest path signal; a cross-category
# content pair (e.g. entity + field co-occurring) is the strongest content
# signal; a lone content token is intentionally tiny.
_WEIGHTS = {
    "expects": 1.0,
    "expected_extraction": 1.0,
    "path_segment": 0.35,
    "path_basename": 0.25,
    "path_substring": 0.15,
    "content_pair": 0.35,
    "content_token": 0.12,
    "import_neighbor": 0.30,
    "test_map": 0.20,
}

# Generic verb classification for obligation derivation. These are ENGLISH
# verb-shape tokens about *what an operation does*, not domain or framework
# nouns — they encode no project knowledge.
_WRITE_VERBS = frozenset(
    {
        "create",
        "add",
        "insert",
        "new",
        "update",
        "edit",
        "modify",
        "change",
        "patch",
        "put",
        "post",
        "save",
        "persist",
        "store",
        "delete",
        "remove",
        "destroy",
    }
)

# A generic token denoting the API/server surface. ``api`` is an architectural
# token, not a framework name.
_API_SURFACE_TOKENS = frozenset({"api", "server", "endpoint", "route", "backend"})

# Machine-generated code must NEVER be a patch target: it is reproduced from a
# spec/source, so a hand patch is futile (overwritten on regeneration) and only
# pollutes the impact set. Detected by a conventional ``generated`` path segment
# OR a generated-marker header — both are cross-ecosystem conventions, not
# project/framework specifics.
_GENERATED_DIR_SEGMENTS = frozenset({"generated", "__generated__", "_generated"})
_GENERATED_MARKERS = (
    "@generated",
    "do not edit",
    "code generated by",
    "auto-generated",
    "autogenerated",
    "this file is generated",
    "this is a generated file",
)
_GENERATED_SCAN_BYTES = 2000


def _is_generated(rel_path: str, project_root: Path) -> bool:
    """True for machine-generated code that must not be hand-patched."""
    parts = {p.lower() for p in Path(rel_path).parts}
    if parts & _GENERATED_DIR_SEGMENTS:
        return True
    try:
        head = (
            (project_root / rel_path)
            .read_text(encoding="utf-8")[:_GENERATED_SCAN_BYTES]
            .lower()
        )
    except (OSError, UnicodeDecodeError):
        return False
    return any(marker in head for marker in _GENERATED_MARKERS)


# ---------------------------------------------------------------------------
# Data model
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class ImpactEvidence:
    """A single piece of evidence that a file belongs in the impact set."""

    source: str
    detail: str
    weight: float
    # Which analysis category produced the matched term, when known:
    # "entity" | "field" | "operation" | "surface" | "" (unknown / graph).
    category: str = ""


@dataclass
class ImplCandidate:
    """A candidate implementation file plus the evidence gathered for it."""

    path: str
    score: float = 0.0
    evidences: list[ImpactEvidence] = field(default_factory=list)
    accepted: bool = False
    reject_reason: str = ""

    def sources(self) -> set[str]:
        return {e.source for e in self.evidences}

    def categories(self) -> set[str]:
        return {e.category for e in self.evidences if e.category}

    def terms(self) -> set[str]:
        return {e.detail for e in self.evidences}


@dataclass
class ImpactObligation:
    """A change facet the phenomenon implies that the plan must cover."""

    id: str
    description: str
    # A candidate covers this obligation when it carries evidence for at least
    # one token in EACH non-empty requirement group below.
    required_surface: list[str] = field(default_factory=list)
    required_entity: bool = True
    required_operation: list[str] = field(default_factory=list)


@dataclass
class ImpactPlan:
    """The resolved impact plan returned by :func:`resolve_impact_plan`."""

    design_node_ids: list[str]
    impl_paths: list[str]
    test_paths: list[str]
    candidates: list[ImplCandidate]
    obligations: list[ImpactObligation]
    covered_obligations: dict[str, list[str]]
    unresolved_obligations: list[str]
    status: Literal["complete", "ambiguous", "incomplete"]
    diagnostics: list[str] = field(default_factory=list)


# ---------------------------------------------------------------------------
# Term derivation (typed by analysis category)
# ---------------------------------------------------------------------------


import re as _re

_CAMEL_BOUNDARY_RE = _re.compile(r"(?<=[a-z0-9])(?=[A-Z])|(?<=[A-Z])(?=[A-Z][a-z])")
_NON_ALNUM_RE = _re.compile(r"[^A-Za-z0-9]+")


def _split_words_local(term: str) -> list[str]:
    """Split a term into component words (snake/kebab/camel aware)."""
    if not term:
        return []
    spaced = _NON_ALNUM_RE.sub(" ", term)
    spaced = _CAMEL_BOUNDARY_RE.sub(" ", spaced)
    return [w for w in spaced.split() if w]


def _singularize_local(word: str) -> str:
    """Cheap, language-agnostic singularizer (common English endings only)."""
    low = word
    if len(low) > 3 and low.endswith("ies"):
        return low[:-3] + "y"
    if len(low) > 4 and low.endswith("ses"):
        return low[:-2]
    if len(low) > 2 and low.endswith("s") and not low.endswith("ss"):
        return low[:-1]
    return low


@dataclass
class _Category:
    """One analysis category: an ordered list of CANONICAL tokens (one per
    original input term, used for obligation ids) plus the full set of
    normalized VARIANTS (used for path/content matching)."""

    canon: list[str] = field(default_factory=list)
    variants: set[str] = field(default_factory=set)


def _build_category(seeds: Iterable[str]) -> _Category:
    """Canonicalize each seed to a single stable token; expand variants.

    The canonical token is the snake-cased singular form of the seed (a
    camelCase seed becomes snake_case; a plural seed becomes singular).
    Variants are the full :func:`normalize_terms` expansion so a file matches regardless
    of casing/plurality. Non-ASCII seeds (e.g. Japanese subject terms) yield no
    ASCII canonical token and contribute variants only.
    """
    canon: list[str] = []
    seen_canon: set[str] = set()
    variants: set[str] = set()
    for seed in seeds:
        if not isinstance(seed, str):
            continue
        seed = seed.strip()
        if not seed:
            continue
        token_variants = normalize_terms([seed])
        variants |= token_variants
        # Canonical: snake of the singular of the seed; skip if not ASCII-wordy.
        canonical = _canonical_token(seed)
        if canonical and canonical not in seen_canon:
            seen_canon.add(canonical)
            canon.append(canonical)
    return _Category(canon=canon, variants=variants)


def _canonical_token(seed: str) -> str:
    """Stable canonical token for an obligation id (snake, singular, ascii)."""
    words = _split_words_local(seed)
    if not words:
        return ""
    words = [w.lower() for w in words]
    words[-1] = _singularize_local(words[-1])
    token = "_".join(words)
    # Reject tokens with no ascii letters (e.g. pure-numeric or empty).
    if not any(c.isalpha() for c in token):
        return ""
    return token


@dataclass
class _TermSets:
    """Category-tagged terms derived from a phenomenon analysis."""

    entity: _Category
    field: _Category
    operation: _Category
    surface: _Category

    @property
    def all(self) -> set[str]:
        return (
            self.entity.variants
            | self.field.variants
            | self.operation.variants
            | self.surface.variants
        )

    def category_of(self, token: str) -> str:
        # Precedence: entity > field > operation > surface. A token is normally
        # in one bucket; precedence only matters for accidental overlaps.
        if token in self.entity.variants:
            return "entity"
        if token in self.field.variants:
            return "field"
        if token in self.operation.variants:
            return "operation"
        if token in self.surface.variants:
            return "surface"
        return ""

    def variants_for_canon(self, category: _Category, canon: str) -> set[str]:
        """All matching variants for a single canonical token in ``category``."""
        return {v for v in category.variants if _canonical_token(v) == canon}


def _derive_term_sets(
    analysis: PhenomenonAnalysis,
    design_updates: Iterable[Any] = (),
) -> _TermSets:
    """Build category-tagged term sets from the analysis.

    Falls back to ``subject_terms``/``lexicon_hits`` as entity-ish seeds when
    the richer decomposition is absent, so the planner degrades gracefully for
    callers (and LLMs) that supply only the legacy fields.
    """
    entity_seeds = list(analysis.entities)
    field_seeds = list(analysis.fields)
    op_seeds = list(analysis.operations)
    surface_seeds = list(analysis.surfaces)

    if not entity_seeds:
        # Legacy fallback: treat subject terms + lexicon hits as entity-ish
        # discovery seeds so brownfield without LLM decomposition still searches.
        entity_seeds = list(analysis.subject_terms) + list(analysis.lexicon_hits)

    # Design-diff identifiers are deliberately NOT folded into the FIELD category.
    # A generated design paragraph emits many generic identifiers (entity,
    # surface and verb words), and dumping them into `field` dilutes the field
    # discriminator until "field evidence" matches almost any file (observed:
    # 56-candidate over-match on a real brownfield repo even with the field
    # requirement on). The discriminating field signal is the LLM-declared
    # `analysis.fields` only; diff text is already reflected via the design-doc
    # update itself, not by widening the search vocabulary.

    return _TermSets(
        entity=_build_category(entity_seeds),
        field=_build_category(field_seeds),
        operation=_build_category(op_seeds),
        surface=_build_category(surface_seeds),
    )


def _design_diff_terms(design_updates: Iterable[Any]) -> list[str]:
    """Extract added-identifier tokens from design-doc diffs (best effort)."""
    out: list[str] = []
    for update in design_updates or ():
        diff = getattr(update, "diff", "") or ""
        for line in diff.splitlines():
            if not line.startswith("+") or line.startswith("+++"):
                continue
            # Pull identifier-ish tokens from added lines only.
            token = ""
            for ch in line[1:]:
                if ch.isalnum() or ch == "_":
                    token += ch
                else:
                    if len(token) >= 4:
                        out.append(token)
                    token = ""
            if len(token) >= 4:
                out.append(token)
    return out


# ---------------------------------------------------------------------------
# Obligation derivation
# ---------------------------------------------------------------------------


def _coerce_llm_obligations(
    analysis: PhenomenonAnalysis,
    terms: _TermSets,
) -> list[ImpactObligation]:
    """Convert LLM-proposed obligation dicts into typed obligations.

    The LLM's ``terms`` are split into surface/operation requirements using the
    same category sets. Entity coverage is always required (a change facet that
    touches none of the feature entities is not this feature's facet).
    """
    out: list[ImpactObligation] = []
    for raw in analysis.obligations or []:
        if not isinstance(raw, dict):
            continue
        oid = str(raw.get("id", "") or "").strip()
        if not oid:
            continue
        norm = normalize_terms(raw.get("terms") or [])
        out.append(
            ImpactObligation(
                id=oid,
                description=str(raw.get("description", "") or "").strip(),
                required_surface=sorted(norm & terms.surface.variants),
                required_entity=True,
                required_operation=sorted(norm & terms.operation.variants),
            )
        )
    return out


def _derive_baseline_obligations(terms: _TermSets) -> list[ImpactObligation]:
    """Deterministic baseline obligation set, used when the LLM proposes none.

    Generic and surface-anchored (no domain knowledge required):

    * one ``surface.<S>`` obligation per CANONICAL surface token — the feature
      must reach that surface (covered by surface-token + entity evidence);
    * one ``api.<op>`` obligation per CANONICAL write-operation token when an
      API-like surface is present — writes must be persisted on the server.

    Ids are built from the canonical (snake/singular) token only, never from
    every cased/plural variant, so the set stays stable. Matching, however, is
    against the full variant set so a file matches in any casing convention.

    The exact id strings are not semantically derivable from flat analysis
    lists without domain knowledge (which would break generality), so the
    baseline keeps ids mechanical. The richer ``render.<surface>`` /
    ``input.<surface>`` shapes are the LLM's job to propose; this baseline only
    guarantees coverage is *checkable* even with no LLM decomposition.
    """
    obligations: list[ImpactObligation] = []
    api_tokens = sorted(terms.surface.variants & _api_surface_variants())
    has_api_surface = bool(api_tokens)
    write_variants = _write_verb_variants()

    # One obligation per canonical surface token.
    for surface_canon in terms.surface.canon:
        variants = sorted(terms.variants_for_canon(terms.surface, surface_canon))
        if not variants:
            continue
        obligations.append(
            ImpactObligation(
                id=f"surface.{surface_canon}",
                description=f"feature must reach the '{surface_canon}' surface",
                required_surface=variants,
                required_entity=True,
            )
        )

    # Write-operation obligations anchored on the API surface.
    if has_api_surface:
        for op_canon in terms.operation.canon:
            if op_canon not in write_variants:
                continue
            op_variants = sorted(terms.variants_for_canon(terms.operation, op_canon))
            if not op_variants:
                continue
            obligations.append(
                ImpactObligation(
                    id=f"api.{op_canon}",
                    description=f"API persists the '{op_canon}' operation",
                    required_surface=api_tokens,
                    required_entity=True,
                    required_operation=op_variants,
                )
            )

    return obligations


def _api_surface_variants() -> set[str]:
    return normalize_terms(_API_SURFACE_TOKENS)


def _write_verb_variants() -> set[str]:
    return normalize_terms(_WRITE_VERBS)


# ---------------------------------------------------------------------------
# Candidate gathering
# ---------------------------------------------------------------------------


def _add_evidence(
    candidates: dict[str, ImplCandidate],
    path: str,
    evidence: ImpactEvidence,
) -> None:
    norm_path = Path(path).as_posix()
    cand = candidates.get(norm_path)
    if cand is None:
        cand = ImplCandidate(path=norm_path)
        candidates[norm_path] = cand
    # De-duplicate identical (source, detail) evidence.
    for existing in cand.evidences:
        if existing.source == evidence.source and existing.detail == evidence.detail:
            return
    cand.evidences.append(evidence)


def _gather_dag_exact(
    candidates: dict[str, ImplCandidate],
    dag: Any,
    design_node_ids: list[str],
    project_root: Path,
) -> dict[str, str]:
    """(a) Existing DAG-exact targets via forward ``expects`` edges."""
    sources: dict[str, str] = {}
    for node_id in design_node_ids:
        targets = affected_impl_targets(dag, node_id, project_root=project_root)
        sources[node_id] = targets.source
        if targets.source == "expects":
            for path in targets.impl_paths:
                _add_evidence(
                    candidates,
                    path,
                    ImpactEvidence(
                        source="expects",
                        detail=node_id,
                        weight=_WEIGHTS["expects"],
                    ),
                )
    return sources


def _gather_module_fallback(
    candidates: dict[str, ImplCandidate],
    dag: Any,
    design_node_ids: list[str],
    project_root: Path,
    terms: _TermSets,
) -> None:
    """(b) Coarse frontmatter ``modules`` glob fallback (legacy resolver).

    Module-path hits are NOT a hard source: per the spec they must be
    corroborated by phenomenon/diff content evidence before acceptance. So we
    record them as ``path_segment``-class soft evidence only when the matched
    file ALSO carries a feature term — a bare module glob can no longer admit a
    file by itself.
    """
    nodes = getattr(dag, "nodes", {}) or {}
    modules: set[str] = set()
    for node_id in design_node_ids:
        node = nodes.get(node_id)
        if node is None:
            continue
        attributes = getattr(node, "attributes", None) or {}
        frontmatter = attributes.get("frontmatter") or {}
        if isinstance(frontmatter, dict):
            mod = frontmatter.get("modules") or []
            if isinstance(mod, (list, tuple)):
                modules.update(str(m) for m in mod)
            elif mod:
                modules.add(str(mod))

    for module in modules:
        for rel in find_impl_candidates(project_root, module):
            norm = Path(rel).as_posix()
            # Only record if the file independently matches a feature term.
            full = project_root / rel
            try:
                text = full.read_text(encoding="utf-8")
            except (OSError, UnicodeDecodeError):
                text = ""
            low = text.lower()
            matched = {t for t in terms.all if t in low}
            if not matched:
                continue
            _add_evidence(
                candidates,
                norm,
                ImpactEvidence(
                    source="module_path",
                    detail=module,
                    weight=_WEIGHTS["path_substring"],
                    category="surface",
                ),
            )


def _gather_code_search(
    candidates: dict[str, ImplCandidate],
    project_root: Path,
    terms: _TermSets,
) -> None:
    """(c) Phenomenon/design-diff code search across path + content."""
    hits = find_impl_candidates_v2(project_root, terms.all)
    for rel, info in hits.items():
        # Path-segment evidence (typed by the matched term's category).
        for p_hit in info.get("path_hits", []):
            _add_evidence(
                candidates,
                rel,
                ImpactEvidence(
                    source=p_hit.where,
                    detail=p_hit.term,
                    weight=_WEIGHTS.get(p_hit.where, 0.1),
                    category=terms.category_of(p_hit.term),
                ),
            )

        # Content evidence: lone tokens are weak; a cross-category co-occurrence
        # (entity+field, entity+operation, ...) is a strong INDEPENDENT signal.
        content_terms = [c.term for c in info.get("content_hits", [])]
        content_categories = {
            terms.category_of(t): t for t in content_terms if terms.category_of(t)
        }
        for term in content_terms:
            _add_evidence(
                candidates,
                rel,
                ImpactEvidence(
                    source="content_token",
                    detail=term,
                    weight=_WEIGHTS["content_token"],
                    category=terms.category_of(term),
                ),
            )
        # Emit a content_pair when at least two DIFFERENT categories co-occur.
        if len(content_categories) >= 2:
            ordered = sorted(content_categories.items())
            label = "+".join(f"{cat}:{tok}" for cat, tok in ordered[:3])
            _add_evidence(
                candidates,
                rel,
                ImpactEvidence(
                    source="content_pair",
                    detail=label,
                    weight=_WEIGHTS["content_pair"],
                ),
            )


def _gather_graph_neighbors(
    candidates: dict[str, ImplCandidate],
    dag: Any,
    project_root: Path,
) -> None:
    """(d) Import-graph neighbors of already-strong candidates.

    A file imported-by (or importing) an accepted-strength candidate is a soft
    corroborating signal — never sufficient alone (weight is below the soft
    threshold), but it can push a borderline neighbor over with other evidence.
    """
    nodes = getattr(dag, "nodes", {}) or {}
    edges = getattr(dag, "edges", []) or []

    # Map rel-path <-> node-id for the candidates we already have.
    path_to_node: dict[str, str] = {}
    for node in nodes.values():
        node_path = str(getattr(node, "path", "") or node.id)
        path_to_node[Path(node_path).as_posix()] = node.id

    # Strong seeds: candidates whose current evidence already crosses a path or
    # content_pair signal (cheap proxy; full scoring happens later).
    seed_paths = {
        c.path
        for c in candidates.values()
        if c.sources() & {"path_segment", "path_basename", "content_pair", "expects"}
    }
    seed_nodes = {path_to_node[p] for p in seed_paths if p in path_to_node}
    if not seed_nodes:
        return

    import_kinds = {"imports", "imported_by", "depends_on"}
    for edge in edges:
        if edge.kind not in import_kinds:
            continue
        for endpoint in (edge.from_id, edge.to_id):
            other = edge.to_id if endpoint == edge.from_id else edge.from_id
            if endpoint not in seed_nodes:
                continue
            node = nodes.get(other)
            if node is None:
                continue
            other_path = Path(str(node.path or node.id)).as_posix()
            if is_test_path(other_path):
                continue
            if not _looks_like_source(other_path):
                continue
            _add_evidence(
                candidates,
                other_path,
                ImpactEvidence(
                    source="import_neighbor",
                    detail=endpoint,
                    weight=_WEIGHTS["import_neighbor"],
                ),
            )


def _looks_like_source(rel_path: str) -> bool:
    return not rel_path.endswith(".md")


# ---------------------------------------------------------------------------
# Scoring & acceptance
# ---------------------------------------------------------------------------


def _score_and_accept(
    candidate: ImplCandidate,
    *,
    min_score: float,
    min_independent_sources: int,
    require_field_evidence: bool = False,
) -> None:
    candidate.score = round(sum(e.weight for e in candidate.evidences), 4)
    sources = candidate.sources()

    # Hard graph evidence is sufficient on its own.
    if sources & HARD_SOURCES:
        candidate.accepted = True
        return

    independent = sources - _NON_INDEPENDENT_SOURCES
    if len(independent) < min_independent_sources:
        candidate.accepted = False
        candidate.reject_reason = (
            f"only {len(independent)} independent evidence source(s) "
            f"(need >= {min_independent_sources})"
        )
        return

    if candidate.score < min_score:
        candidate.accepted = False
        candidate.reject_reason = (
            f"score {candidate.score:.2f} < threshold {min_score:.2f}"
        )
        return

    categories = candidate.categories()
    if "entity" not in categories:
        candidate.accepted = False
        candidate.reject_reason = "no entity evidence"
        return

    # Precision: when the phenomenon names specific data field(s), that field is
    # the discriminator. Generic surface/operation tokens (api, admin, create,
    # update, get) are ubiquitous in a real codebase and over-match if they
    # alone admit a file; require the named field's evidence so acceptance
    # narrows to files that actually touch the feature's data. This is a general
    # inference rule (a feature touching field F lives in files referencing F),
    # not a project/framework-specific carve-out. Field-less features fall back
    # to the field-or-operation signal.
    if require_field_evidence:
        if "field" not in categories:
            candidate.accepted = False
            candidate.reject_reason = (
                "no field evidence (phenomenon names specific field(s); the "
                "field is the discriminator over generic surface/operation tokens)"
            )
            return
    elif not ({"field", "operation"} & categories):
        candidate.accepted = False
        candidate.reject_reason = "no field-or-operation evidence"
        return

    candidate.accepted = True


# ---------------------------------------------------------------------------
# Coverage
# ---------------------------------------------------------------------------


def _covers(candidate: ImplCandidate, obligation: ImpactObligation) -> bool:
    """True when an accepted candidate satisfies every required group."""
    cats = candidate.categories()
    terms = candidate.terms()

    if obligation.required_entity and "entity" not in cats:
        return False
    if obligation.required_surface and not (set(obligation.required_surface) & terms):
        return False
    if obligation.required_operation:
        if set(obligation.required_operation) & terms:
            return True
        # WRITE facets (create/update/delete) leave a concrete verb token in the
        # handler, so they keep requiring it — this preserves anti-false-green
        # (an update file must NOT silently "cover" the create facet). READ /
        # DISPLAY facets (display/render/view/list) have NO literal code verb; a
        # candidate that touches the feature's FIELD on the required surface IS
        # handling that facet, so field-on-surface evidence covers it.
        is_write = bool(set(obligation.required_operation) & _write_verb_variants())
        if not is_write and "field" in cats:
            return True
        return False
    return True


# ---------------------------------------------------------------------------
# Public entry point
# ---------------------------------------------------------------------------


def resolve_impact_plan(
    *,
    dag: Any,
    project_root: Path,
    design_node_ids: list[str],
    phenomenon_text: str,
    analysis: PhenomenonAnalysis,
    design_updates: list[Any] | None = None,
    config: dict[str, Any] | None = None,
    max_impl_candidates: int = _DEFAULT_MAX_IMPL_CANDIDATES,
    min_score: float = _DEFAULT_MIN_SCORE,
    min_independent_sources: int = _DEFAULT_MIN_INDEPENDENT_SOURCES,
) -> ImpactPlan:
    """Resolve the implementation/test files a phenomenon fix must touch.

    See the module docstring for the pipeline. Returns an :class:`ImpactPlan`
    whose ``status`` is:

    * ``complete``   — every obligation is covered by an accepted candidate;
    * ``incomplete`` — at least one obligation has no covering candidate;
    * ``ambiguous``  — too many candidates were accepted to apply safely, or no
      obligations could be derived to verify against.

    Only ``complete`` is safe to apply. ``incomplete``/``ambiguous`` MUST be
    fail-fasted by the caller (anti-false-green): a partial apply that looks
    complete is exactly the failure mode this planner exists to prevent.
    """
    project_root = Path(project_root)
    design_updates = design_updates or []
    diagnostics: list[str] = []

    terms = _derive_term_sets(analysis, design_updates)

    # ------------------------------------------------------------------
    # Obligations: LLM proposal if present, else deterministic baseline.
    # ------------------------------------------------------------------
    obligations = _coerce_llm_obligations(analysis, terms)
    if obligations:
        diagnostics.append(f"obligations: {len(obligations)} from LLM proposal")
    else:
        obligations = _derive_baseline_obligations(terms)
        diagnostics.append(
            f"obligations: {len(obligations)} from deterministic baseline"
        )

    # ------------------------------------------------------------------
    # Candidate gathering (a)–(e).
    # ------------------------------------------------------------------
    candidates: dict[str, ImplCandidate] = {}
    dag_sources = _gather_dag_exact(candidates, dag, design_node_ids, project_root)
    if dag_sources:
        diagnostics.append(
            "dag-exact sources: "
            + ", ".join(f"{nid}={src}" for nid, src in sorted(dag_sources.items()))
        )
    _gather_module_fallback(candidates, dag, design_node_ids, project_root, terms)
    _gather_code_search(candidates, project_root, terms)
    _gather_graph_neighbors(candidates, dag, project_root)

    # Drop test files (resolved below), design docs, and machine-generated code
    # (never a hand-patch target — regenerated from source).
    for path in list(candidates):
        if (
            is_test_path(path)
            or path.endswith(".md")
            or _is_generated(path, project_root)
        ):
            del candidates[path]

    # ------------------------------------------------------------------
    # Score & accept.
    # ------------------------------------------------------------------
    field_terms_present = bool(terms.field.variants)
    for cand in candidates.values():
        _score_and_accept(
            cand,
            min_score=min_score,
            min_independent_sources=min_independent_sources,
            require_field_evidence=field_terms_present,
        )

    accepted = sorted(
        (c for c in candidates.values() if c.accepted),
        key=lambda c: (-c.score, c.path),
    )

    # ------------------------------------------------------------------
    # Cardinality guard: too broad => ambiguous (refuse a sweeping patch).
    # ------------------------------------------------------------------
    if len(accepted) > max_impl_candidates:
        diagnostics.append(
            f"too many implementation candidates: {len(accepted)} > "
            f"{max_impl_candidates}; refusing to apply a broad AI patch"
        )
        return ImpactPlan(
            design_node_ids=list(design_node_ids),
            impl_paths=[c.path for c in accepted],
            test_paths=[],
            candidates=sorted(candidates.values(), key=lambda c: c.path),
            obligations=obligations,
            covered_obligations={},
            unresolved_obligations=[o.id for o in obligations],
            status="ambiguous",
            diagnostics=diagnostics,
        )

    impl_paths = [c.path for c in accepted]

    # ------------------------------------------------------------------
    # Resolve tests for accepted impls (DAG tested_by edges + name heuristics).
    # ------------------------------------------------------------------
    test_paths = _resolve_tests(dag, impl_paths, project_root)

    # ------------------------------------------------------------------
    # Obligation coverage.
    # ------------------------------------------------------------------
    covered: dict[str, list[str]] = {}
    unresolved: list[str] = []
    for obligation in obligations:
        covering = [c.path for c in accepted if _covers(c, obligation)]
        if covering:
            covered[obligation.id] = covering
        else:
            unresolved.append(obligation.id)

    # ------------------------------------------------------------------
    # Status.
    # ------------------------------------------------------------------
    if not obligations:
        # Nothing to verify against — cannot prove completeness, so refuse.
        status: Literal["complete", "ambiguous", "incomplete"] = "ambiguous"
        diagnostics.append(
            "no obligations could be derived from the analysis — cannot verify "
            "completeness; refusing to apply (anti-false-green)"
        )
    elif unresolved:
        status = "incomplete"
        diagnostics.append(
            "unresolved obligation(s): " + ", ".join(unresolved)
        )
    elif not impl_paths:
        status = "incomplete"
        diagnostics.append("no implementation candidates accepted")
    else:
        status = "complete"

    return ImpactPlan(
        design_node_ids=list(design_node_ids),
        impl_paths=impl_paths,
        test_paths=test_paths,
        candidates=sorted(candidates.values(), key=lambda c: c.path),
        obligations=obligations,
        covered_obligations=covered,
        unresolved_obligations=unresolved,
        status=status,
        diagnostics=diagnostics,
    )


def _resolve_tests(
    dag: Any,
    impl_paths: list[str],
    project_root: Path,
) -> list[str]:
    """Collect test files for the accepted impl files via DAG ``tested_by``."""
    nodes = getattr(dag, "nodes", {}) or {}
    forward: dict[str, list[str]] = {}
    for edge in getattr(dag, "edges", []) or []:
        if edge.kind == "tested_by":
            forward.setdefault(edge.from_id, []).append(edge.to_id)

    # Map rel-path -> node-id.
    path_to_node: dict[str, str] = {}
    for node in nodes.values():
        node_path = Path(str(node.path or node.id)).as_posix()
        path_to_node[node_path] = node.id

    out: list[str] = []
    seen: set[str] = set()
    for impl in impl_paths:
        node_id = path_to_node.get(impl, impl)
        for test_id in forward.get(node_id, []):
            node = nodes.get(test_id)
            test_path = Path(str((node.path if node else None) or test_id)).as_posix()
            if test_path.endswith(".md"):
                continue
            if test_path not in seen:
                seen.add(test_path)
                out.append(test_path)
    return sorted(out)
