"""stdin/stdout interactive prompt with --non-interactive support."""

from __future__ import annotations

import sys
from dataclasses import dataclass
from typing import IO, Optional


class PromptAbort(Exception):
    """User (or non-interactive default) aborted the operation."""


@dataclass
class Option:
    """A single selectable option."""

    id: str
    label: str
    is_default: bool = False


class InteractivePrompt:
    """A small stdin/stdout I/O wrapper.

    The class is intentionally minimal: it only does display and read.
    Question strings and option labels MUST be generated by the caller
    (from lexicon / LLM). Hardcoded prompts here would break the
    "no hardcoded interactive strings" requirement from the design.
    """

    def __init__(
        self,
        *,
        non_interactive: bool = False,
        on_ambiguity: str = "abort",
        stdin: Optional[IO[str]] = None,
        stdout: Optional[IO[str]] = None,
    ) -> None:
        self.non_interactive = non_interactive
        if on_ambiguity not in {"abort", "default", "top1"}:
            raise ValueError(f"invalid on_ambiguity: {on_ambiguity}")
        self.on_ambiguity = on_ambiguity
        self._stdin = stdin or sys.stdin
        self._stdout = stdout or sys.stdout

    # ------------------------------------------------------------------
    # Public primitives
    # ------------------------------------------------------------------

    def choice(
        self,
        question: str,
        options: list[Option],
        *,
        allow_abort: bool = True,
        allow_all: bool = False,
    ) -> str:
        if not options:
            raise ValueError("choice() requires at least one option")

        if self.non_interactive:
            return self._non_interactive_choice(options)

        self._write(question.rstrip() + "\n")
        for index, option in enumerate(options, start=1):
            marker = " *" if option.is_default else ""
            self._write(f"  {index}) {option.label}{marker}\n")
        suffix_parts = ["number"]
        if allow_all:
            suffix_parts.append("'all'")
        if allow_abort:
            suffix_parts.append("'abort'")
        self._write("Enter " + " / ".join(suffix_parts) + ": ")
        self._flush()

        while True:
            raw = self._read_line()
            if raw is None:
                # EOF — treat as abort
                if allow_abort:
                    raise PromptAbort("EOF on stdin")
                return options[0].id
            answer = raw.strip().lower()
            if allow_abort and answer in {"abort", "a", "q", "quit", "cancel"}:
                raise PromptAbort("user aborted")
            if allow_all and answer == "all":
                return "__all__"
            if answer.isdigit():
                idx = int(answer)
                if 1 <= idx <= len(options):
                    return options[idx - 1].id
            self._write("Invalid selection. ")
            self._flush()

    def text(
        self,
        question: str,
        *,
        allow_abort: bool = True,
        allow_empty: bool = False,
    ) -> str:
        if self.non_interactive:
            if allow_empty:
                return ""
            raise PromptAbort("non-interactive: text input not allowed")

        self._write(question.rstrip() + "\n> ")
        self._flush()
        raw = self._read_line()
        if raw is None:
            if allow_abort:
                raise PromptAbort("EOF on stdin")
            return ""
        answer = raw.strip()
        if allow_abort and answer.lower() in {"abort", "quit", "cancel"}:
            raise PromptAbort("user aborted")
        if not answer and not allow_empty:
            raise PromptAbort("empty input")
        return answer

    def confirm(
        self,
        question: str,
        *,
        default: bool | None = None,
        allow_abort: bool = True,
    ) -> bool:
        if self.non_interactive:
            if default is not None:
                return default
            raise PromptAbort("non-interactive: confirm requires default")

        suffix = "[y/n"
        if allow_abort:
            suffix += "/abort"
        suffix += "]"
        self._write(f"{question.rstrip()} {suffix} ")
        self._flush()
        raw = self._read_line()
        if raw is None:
            if allow_abort:
                raise PromptAbort("EOF on stdin")
            return bool(default)
        answer = raw.strip().lower()
        if allow_abort and answer in {"abort", "a", "q", "quit"}:
            raise PromptAbort("user aborted")
        if answer in {"y", "yes"}:
            return True
        if answer in {"n", "no"}:
            return False
        if not answer and default is not None:
            return default
        raise PromptAbort(f"unrecognized confirm answer: {raw!r}")

    def show_diff(
        self,
        diff_text: str,
        *,
        question: str,
        allow_abort: bool = True,
        accept_default: bool | None = None,
    ) -> str:
        """Display a diff and ask the user whether to apply it.

        Returns: 'accept', 'reject', or raises PromptAbort.
        """
        if self.non_interactive:
            if accept_default is True:
                return "accept"
            if accept_default is False:
                return "reject"
            raise PromptAbort("non-interactive: show_diff requires default")

        self._write(diff_text.rstrip() + "\n")
        try:
            answer = self.confirm(question, default=accept_default, allow_abort=allow_abort)
        except PromptAbort:
            raise
        return "accept" if answer else "reject"

    # ------------------------------------------------------------------
    # Internals
    # ------------------------------------------------------------------

    def _non_interactive_choice(self, options: list[Option]) -> str:
        if self.on_ambiguity == "default":
            for option in options:
                if option.is_default:
                    return option.id
            raise PromptAbort("non-interactive: no default option for choice")
        if self.on_ambiguity == "top1":
            return options[0].id
        raise PromptAbort("non-interactive: ambiguous choice (on_ambiguity=abort)")

    def _read_line(self) -> str | None:
        line = self._stdin.readline()
        if line == "":
            return None
        return line.rstrip("\n")

    def _write(self, text: str) -> None:
        self._stdout.write(text)

    def _flush(self) -> None:
        try:
            self._stdout.flush()
        except Exception:  # noqa: BLE001
            pass
