from pathlib import Path
import re

import yaml
from click.testing import CliRunner

from codd.cli import main
from codd.e2e_generator import TransitionTestGenerator


def _write_transitions(project: Path, edges: list[dict]) -> Path:
    path = project / "docs" / "extracted" / "screen-transitions.yaml"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(yaml.safe_dump({"edges": edges}, sort_keys=False), encoding="utf-8")
    return path


def _edge(**overrides: str) -> dict[str, str]:
    payload = {
        "from": "/login",
        "to": "/admin/dashboard",
        "trigger": "form#signin button[type=submit]",
        "type": "redirect",
        "source_file": "src/components/auth/sign-in-form.tsx",
        "source_line": "78",
    }
    payload.update(overrides)
    return payload


def _write_codd_config(project: Path, runner: str) -> None:
    codd_dir = project / "codd"
    codd_dir.mkdir(parents=True, exist_ok=True)
    (codd_dir / "codd.yaml").write_text(
        yaml.safe_dump({"e2e": {"test_runner": runner}}, sort_keys=False),
        encoding="utf-8",
    )


def test_transition_generator_load_empty_when_no_yaml(tmp_path):
    assert TransitionTestGenerator(tmp_path).load_transitions() == []


def test_transition_generator_load_edges(tmp_path):
    edges = [_edge()]
    _write_transitions(tmp_path, edges)

    assert TransitionTestGenerator(tmp_path).load_transitions() == edges


def test_generate_test_file_playwright_format(tmp_path):
    content = TransitionTestGenerator(tmp_path).generate_test_file([_edge()])

    assert 'import { test, expect } from "@playwright/test";' in content
    assert 'await page.goto("/login");' in content
    assert 'await page.click("form#signin button[type=submit]");' in content
    assert 'await expect(page).toHaveURL("/admin/dashboard");' in content


def test_generate_test_file_no_trigger(tmp_path):
    content = TransitionTestGenerator(tmp_path).generate_test_file([_edge(trigger="")])

    assert "page.click" not in content
    assert 'await expect(page).toHaveURL("/admin/dashboard");' in content


def test_generate_test_file_empty_transitions(tmp_path):
    assert TransitionTestGenerator(tmp_path).generate_test_file([]) == ""


def test_generate_includes_auto_generated_comment(tmp_path):
    content = TransitionTestGenerator(tmp_path).generate_test_file([_edge()])

    assert "Auto-generated by CoDD" in content
    assert "docs/extracted/screen-transitions.yaml" in content


def test_write_tests_creates_file(tmp_path):
    _write_transitions(tmp_path, [_edge()])

    output = TransitionTestGenerator(tmp_path).write_tests(tmp_path / "out" / "transitions.spec.ts")

    assert output.exists()
    assert 'test("transition: /login -> /admin/dashboard (redirect)"' in output.read_text(encoding="utf-8")


def test_write_tests_custom_output_path(tmp_path):
    _write_transitions(tmp_path, [_edge()])
    custom_output = tmp_path / "custom" / "screen.spec.ts"

    output = TransitionTestGenerator(tmp_path).write_tests(custom_output)

    assert output == custom_output
    assert custom_output.exists()


def test_write_tests_default_path(tmp_path):
    _write_transitions(tmp_path, [_edge()])

    output = TransitionTestGenerator(tmp_path).write_tests()

    assert output == tmp_path / "tests" / "e2e" / "screen_transitions.spec.ts"
    assert output.exists()


def test_codd_yaml_test_runner_override(tmp_path):
    _write_codd_config(tmp_path, "custom-runner")

    generator = TransitionTestGenerator(tmp_path)

    assert generator.runner == "custom-runner"


def test_generality_no_playwright_hardcode_in_core():
    source = Path("codd/e2e_generator.py").read_text(encoding="utf-8")

    assert not re.search(r"\bif\b[^\n]*playwright", source, re.IGNORECASE)
    assert not re.search(r"\belif\b[^\n]*playwright", source, re.IGNORECASE)


def test_multiple_transitions_generate_multiple_tests(tmp_path):
    transitions = [
        _edge(**{"from": "/login", "to": "/dashboard", "type": "redirect"}),
        _edge(**{"from": "/settings", "to": "/profile", "type": "link"}),
        _edge(**{"from": "/admin", "to": "/login", "type": "redirect"}),
    ]

    content = TransitionTestGenerator(tmp_path).generate_test_file(transitions)

    assert content.count("test(") == 3


def test_transition_type_in_test_name(tmp_path):
    content = TransitionTestGenerator(tmp_path).generate_test_file([_edge(type="signin_cb")])

    assert "transition: /login -> /admin/dashboard (signin_cb)" in content


def test_all_routes_covered_in_output(tmp_path):
    transitions = [
        _edge(**{"from": "/login", "to": "/dashboard"}),
        _edge(**{"from": "/dashboard", "to": "/settings"}),
    ]

    content = TransitionTestGenerator(tmp_path).generate_test_file(transitions)

    for route in ["/login", "/dashboard", "/settings"]:
        assert route in content


def test_cli_e2e_generate_transitions_mode_writes_custom_file(tmp_path):
    _write_transitions(tmp_path, [_edge()])
    runner = CliRunner()

    result = runner.invoke(
        main,
        ["e2e-generate", "--path", str(tmp_path), "--mode", "transitions", "--output", "e2e/transitions.spec.ts"],
    )

    assert result.exit_code == 0
    assert "Generated transition test file: e2e/transitions.spec.ts (1 transitions)" in result.output
    assert (tmp_path / "e2e" / "transitions.spec.ts").exists()


def test_cli_e2e_group_generate_transitions_mode_writes_default_file(tmp_path):
    _write_transitions(tmp_path, [_edge()])
    runner = CliRunner()

    result = runner.invoke(main, ["e2e", "generate", "--path", str(tmp_path), "--mode", "transitions"])

    assert result.exit_code == 0
    assert "Generated transition test file: tests/e2e/screen_transitions.spec.ts (1 transitions)" in result.output
    assert (tmp_path / "tests" / "e2e" / "screen_transitions.spec.ts").exists()
