"""Tests for GitHub Action PR comment formatter."""

from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path

SCRIPT = Path(__file__).parent.parent / "scripts" / "format_pr_comment.py"


def _run_formatter(report_path: str) -> str:
    result = subprocess.run(
        [sys.executable, str(SCRIPT), report_path],
        capture_output=True,
        text=True,
    )
    return result.stdout


def _make_report(*, verdict="APPROVE", v_errors=0, v_warnings=0, p_critical=0, p_warnings=0, review=None) -> dict:
    return {
        "timestamp": "2026-04-04T00:00:00Z",
        "diff_target": "origin/main",
        "verdict": verdict,
        "risk_level": {"APPROVE": "LOW", "CONDITIONAL": "MEDIUM", "REJECT": "HIGH"}[verdict],
        "changed_files": ["src/foo.py"],
        "validation": {
            "status": "PASS" if v_errors == 0 else "FAIL",
            "documents_checked": 5,
            "errors": v_errors,
            "warnings": v_warnings,
            "issues": [{"level": "ERROR", "code": "E001", "location": "doc.md", "message": "broken"}] * v_errors,
        },
        "impact": {"affected_nodes": 2, "nodes": {}},
        "convention_alerts": [],
        "policy": {
            "status": "PASS" if p_critical == 0 else "FAIL",
            "files_checked": 10,
            "rules_applied": 3,
            "critical": p_critical,
            "warnings": p_warnings,
            "violations": [
                {"rule_id": "SEC-001", "severity": "CRITICAL", "file": "src/bad.py", "line": 5, "message": "forbidden"}
            ] * p_critical,
        },
        "review": review,
        "action_required": "Safe to merge." if verdict == "APPROVE" else "Review needed.",
    }


class TestFormatPrComment:
    def test_approve_report(self, tmp_path):
        report = tmp_path / "report.json"
        report.write_text(json.dumps(_make_report()))
        output = _run_formatter(str(report))
        assert "APPROVE" in output
        assert ":white_check_mark:" in output
        assert "Safe to merge" in output

    def test_reject_report(self, tmp_path):
        report = tmp_path / "report.json"
        report.write_text(json.dumps(_make_report(verdict="REJECT", v_errors=1)))
        output = _run_formatter(str(report))
        assert "REJECT" in output
        assert ":x:" in output

    def test_policy_violations_shown(self, tmp_path):
        report = tmp_path / "report.json"
        report.write_text(json.dumps(_make_report(verdict="REJECT", p_critical=1)))
        output = _run_formatter(str(report))
        assert "SEC-001" in output
        assert "src/bad.py:5" in output

    def test_changed_files_shown(self, tmp_path):
        report = tmp_path / "report.json"
        report.write_text(json.dumps(_make_report()))
        output = _run_formatter(str(report))
        assert "src/foo.py" in output

    def test_review_skipped(self, tmp_path):
        report = tmp_path / "report.json"
        report.write_text(json.dumps(_make_report()))
        output = _run_formatter(str(report))
        assert "SKIPPED" in output

    def test_review_included(self, tmp_path):
        review = {"pass_count": 3, "fail_count": 1, "avg_score": 72.5, "results": []}
        report = tmp_path / "report.json"
        report.write_text(json.dumps(_make_report(verdict="CONDITIONAL", review=review)))
        output = _run_formatter(str(report))
        assert "3 pass" in output
        assert "1 fail" in output

    def test_missing_file_shows_error(self, tmp_path):
        output = _run_formatter(str(tmp_path / "nonexistent.json"))
        assert "failed to run" in output

    def test_codd_footer(self, tmp_path):
        report = tmp_path / "report.json"
        report.write_text(json.dumps(_make_report()))
        output = _run_formatter(str(report))
        assert "Generated by" in output
        assert "CoDD" in output
