#!/usr/bin/env python3
"""Format CoDD audit JSON into a GitHub PR comment body.

Usage: python3 format_pr_comment.py /path/to/audit.json
Output: Writes 'body' to GITHUB_OUTPUT (multiline format).
"""

from __future__ import annotations

import json
import os
import sys


def format_comment(data: dict) -> str:
    verdict = data["verdict"]
    risk = data["risk_level"]
    icon = {"APPROVE": ":white_check_mark:", "CONDITIONAL": ":warning:", "REJECT": ":x:"}.get(verdict, ":question:")

    lines = [
        f"## CoDD Audit: {icon} {verdict}",
        "",
        f"**Risk Level**: {risk}",
        "",
        "| Check | Status | Details |",
        "|-------|--------|---------|",
    ]

    # Validation
    v = data["validation"]
    v_icon = ":white_check_mark:" if v["errors"] == 0 else ":x:"
    lines.append(f'| Validation | {v_icon} {v["status"]} | {v["documents_checked"]} docs, {v["errors"]} errors, {v["warnings"]} warnings |')

    # Policy
    p = data["policy"]
    p_icon = ":white_check_mark:" if p["status"] == "PASS" else ":x:"
    lines.append(f'| Policy | {p_icon} {p["status"]} | {p["files_checked"]} files, {p["critical"]} critical, {p["warnings"]} warnings |')

    # Impact
    imp = data["impact"]
    lines.append(f'| Impact | :mag: | {imp["affected_nodes"]} affected nodes |')

    # Review
    if data.get("review"):
        r = data["review"]
        r_icon = ":white_check_mark:" if r["fail_count"] == 0 else ":warning:"
        lines.append(f'| Review | {r_icon} | {r["pass_count"]} pass, {r["fail_count"]} fail (avg {r["avg_score"]}) |')
    else:
        lines.append("| Review | :fast_forward: SKIPPED | |")

    lines.append("")
    lines.append(f"**Action**: {data['action_required']}")

    # Changed files
    changed = data.get("changed_files", [])
    if changed:
        lines.append("")
        lines.append(f"<details><summary>Changed Files ({len(changed)})</summary>")
        lines.append("")
        for f in changed:
            lines.append(f"- `{f}`")
        lines.append("")
        lines.append("</details>")

    # Issues
    violations = p.get("violations", [])
    v_issues = v.get("issues", [])
    if violations or v_issues:
        lines.append("")
        lines.append("<details><summary>Issues Found</summary>")
        lines.append("")
        for vi in v_issues:
            lines.append(f"- **[{vi['level']}]** {vi['location']}: {vi['message']}")
        for pv in violations:
            loc = f"{pv['file']}:{pv['line']}" if pv.get("line") else pv["file"]
            lines.append(f"- **[{pv['severity']}]** {loc} ({pv['rule_id']}): {pv['message']}")
        lines.append("")
        lines.append("</details>")

    lines.append("")
    lines.append("---")
    lines.append("*Generated by [CoDD](https://github.com/yohey-w/codd-dev) audit*")

    return "\n".join(lines)


def main() -> None:
    if len(sys.argv) < 2:
        print("Usage: format_pr_comment.py <audit.json>", file=sys.stderr)
        sys.exit(1)

    report_path = sys.argv[1]

    try:
        with open(report_path) as f:
            data = json.load(f)
    except (FileNotFoundError, json.JSONDecodeError):
        body = "## CoDD Audit\n\n:x: Audit failed to run. Check workflow logs."
        print(f"body<<GHEOF\n{body}\nGHEOF")
        return

    body = format_comment(data)
    print(f"body<<GHEOF\n{body}\nGHEOF")


if __name__ == "__main__":
    main()
